### ISSUE TITLE
a problem about kmeans algorithm to get the prior anchors

### ISSUE THREAD

**Issue by PanJinquan** [wizyoung/YOLOv3_TensorFlow#10]
您好，博主，我细看了源码，有个地方很不懂！其中get_kmeans.py的kmean聚类prior anchors时，所使用的数据[W,H]是没有scale到[0,1]，但在训练时scale了anchor_w = anchor_w / W * 416, anchor_h = anchor_g / H * 416，我想问的是将样本数据[W,H]宽高scale到[0,1]，再kmean聚类会不会更好？望回复~，谢谢~

**Comment by wizyoung** [comment]
最终回归坐标的时候，所采用的 anchor 是相对于最后 resize 的图的大小的，也就是说 anchor 也要和原图一起缩放，这样尺度才会匹配。为什么我做 kmeans 的时候直接对原图操作，训练时再将 anchor 进行对应 resize 呢，是因为 YOLO v3 有个多尺度训练技巧，可以参加论文，比如可以先 416 大小的图训练几个 epoch 再用 608 大小的图训练，如此反复交替，显然 416 的图和 608 的图所用的 anchor 是不一样的。至于你说的 scale 到 [0, 1] 问题，做不做其实不影响的聚类效果的。

**Comment by hktxt** [comment]
`x = np.minimum(clusters[:, 0], box[0])`
`y = np.minimum(clusters[:, 1], box[1])`
` if np.count_nonzero(x == 0) > 0 or np.count_nonzero(y == 0) > 0:` 
        ` raise ValueError("Box has no area")`


`intersection = x * y`
`box_area = box[0] * box[1]`

不是很明白为什么这里intersection是 `x*y`  ?

**Comment by wizyoung** [comment]
@hktxt box 的中心对齐
