### ISSUE TITLE
video_test

### ISSUE THREAD

**Issue by hehern** [wizyoung/YOLOv3_TensorFlow#100]
１．When I executed the train.py file, I got some files under checkpoint, such as: best_model_Epoch_160_step_644.0_mAP_1.0000_loss_18.3900_lr_0.0002821032.data-00000-of-00001
best_model_Epoch_160_step_644.0_mAP_1.0000_loss_18.3900_lr_0.0002821032.index
best_model_Epoch_160_step_644.0_mAP_1.0000_loss_18.3900_lr_0.0002821032.meta
Are these weights files?
2.I want to run video_test.py, where should I set the path of the weight file?

Looking forward to your reply

**Comment by OtabekToshkanov** [comment]
> １．When I executed the train.py file, I got some files under checkpoint, such as: best_model_Epoch_160_step_644.0_mAP_1.0000_loss_18.3900_lr_0.0002821032.data-00000-of-00001
> best_model_Epoch_160_step_644.0_mAP_1.0000_loss_18.3900_lr_0.0002821032.index
> best_model_Epoch_160_step_644.0_mAP_1.0000_loss_18.3900_lr_0.0002821032.meta
> Are these weights files?
> 2.I want to run video_test.py, where should I set the path of the weight file?
> 
> Looking forward to your reply

you should put "best_model_Epoch_160_step_644.0_mAP_1.0000_loss_18.3900_lr_0.0002821032" to default weigth path

**Comment by hehern** [comment]
> > １．When I executed the train.py file, I got some files under checkpoint, such as: best_model_Epoch_160_step_644.0_mAP_1.0000_loss_18.3900_lr_0.0002821032.data-00000-of-00001
> > best_model_Epoch_160_step_644.0_mAP_1.0000_loss_18.3900_lr_0.0002821032.index
> > best_model_Epoch_160_step_644.0_mAP_1.0000_loss_18.3900_lr_0.0002821032.meta
> > Are these weights files?
> > 2.I want to run video_test.py, where should I set the path of the weight file?
> > Looking forward to your reply
> 
> you should put "best_model_Epoch_160_step_644.0_mAP_1.0000_loss_18.3900_lr_0.0002821032" to default weigth path

thanks, i have found the path:"/data/darknet_weigths"
