### ISSUE TITLE
从已经训练好的模型开始新的训练碰到问题

### ISSUE THREAD

**Issue by LowWisdom** [wizyoung/YOLOv3_TensorFlow#101]
首先谢谢作者分享了这么好的代码。
我按照作者推荐的训练方式，第一步将learning_rate设置为1e-3，在自己制作的训练集上（大概256张图片）训练80epochs后得到权重文件，但检测效果不太好。第二步想在上一步的权重上，降低learning_rate为1e-4，并修改了args.py中的restore_path=‘./myweight/yolov3v2.ckpt’（上一步的权重路径），开始训练，发现1st epoch结束后，tota_loss达到几十万。这是不是说明又重新开始训练了？还有哪里需要设置的？
第一次复现YOLOv3，小白一个。

**Comment by wizyoung** [comment]
记得修改 args.py 里面的 global step 值。
可以尝试直接单阶段训，优化器设置为 momentum (adam 容易梯度爆炸) 试试看

**Comment by wizyoung** [comment]
感觉不太正常，难道是 ckpt 里面没有存下 优化器 的历史信息吗，回头我check一下代码。

anchor 有自己去聚类么，聚类后有resize到输入尺寸么，效果差不太应该

**Comment by LowWisdom** [comment]
多谢多谢！anchors用get_kmeans计算得到的，按照您说的步骤操作。运行test_singel_image.py时加入了--new size参数（按照我自己数据集图片的宽度和高度），另外我的batch_size=16，训练样本数256个，val样本数64，采用了multi_scale_train=True，其他都是您程序默认的，没有修改。真是奇怪了。

**Comment by LowWisdom** [comment]
> 感觉不太正常，难道是 ckpt 里面没有存下 优化器 的历史信息吗，回头我check一下代码。
> 
> anchor 有自己去聚类么，聚类后有resize到输入尺寸么，效果差不太应该

您好！请问一下，在之前的权重基础上再训练的问题有了解决方案么？昨天测试结果不好，问题在于我自己标注的数据集不太准确导致的，今天重新训练后好些了。另外，我还发现了一个小bug，运行eval.py出错，提示，AverageMeter没有avg属性，老版本软件里有。

**Comment by wizyoung** [comment]
检查了下，发现github上的版本不对。现在新版本能载入优化器动量了，之前代码没更新。
avg 属性已修正，感谢

**Comment by wizyoung** [comment]
修正细节参考：https://github.com/wizyoung/YOLOv3_TensorFlow/commit/e7a314ecc8bf3957901d8ef21b6d5aa199419ee6#diff-e44f4a60e89e820dde9bb27afa634965R112
