### ISSUE TITLE
Question about upsampling function

### ISSUE THREAD

**Issue by Cli98** [wizyoung/YOLOv3_TensorFlow#103]
Hi everyone,

Can anyone tell me, for upsample_layer function(in layer_util.py), why should we use resize_nearest_neighbor method instead of upsampling function offered by tensorflow？

Thank you

**Comment by wizyoung** [comment]
This comes from the yolo source code. see yolo cfg here: https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-voc.cfg#L630

yolo uses the nearest neighbor resizing.

**Comment by Cli98** [comment]
@wizyoung Thank you and good to know this.

Please allow me to follow-up. You just said "yolo uses the nearest neighbor resizing". Do you have any reference to it? I will be appreciate if you can point me out some clues. I do checked the link you attached but I do not think it suggests what you said above.

**Comment by wizyoung** [comment]
@Cli98 The C source code of the upsample layer in the config file is defined here: https://github.com/pjreddie/darknet/blob/master/src/blas.c#L334. So you see, it's the nearest neighbor resize.

**Comment by Cli98** [comment]
@wizyoung My bad. I'm not quite familiar with C. Still thank you for your kindly response.

**Comment by wizyoung** [comment]
Actually, I think is a good question. So I will mark it as good first issue tag.
