### ISSUE TITLE
How does fix_padding work

### ISSUE THREAD

**Issue by Cli98** [wizyoung/YOLOv3_TensorFlow#104]
Hi everyone,

I wonder if someone can discuss how _fix_padding function work?

Thank you

**Comment by wizyoung** [comment]
This comes from the yolo source code. see yolo cfg here: https://github.com/pjreddie/darknet/blob/master/cfg/yolov3-spp.cfg#L30.

pad = 1 means padding 1 pixel at left while keeping the same image size after padding.

**Comment by Cli98** [comment]
Thanks for your kindly response.
