### ISSUE TITLE
run video_test.py only get 72ms per 1 image

### ISSUE THREAD

**Issue by nightfuryyy** [wizyoung/YOLOv3_TensorFlow#111]
Hi wizyoung:
I ran video_test.py on GPU colab (tesla k80) and get that time:
0.07921981811523438
0.07713556289672852
0.07343196868896484
0.07469964027404785
0.07210373878479004

x2.5 slower than your.

Could you help me a little bit with this?

Thank you!

**Comment by wizyoung** [comment]
tesla k80 is kind of slow as its compute capability is only 3.7. However, the compute capability of titan x is 6.1. 
Refer to the running speed of k80 on the original yolov3 model: https://github.com/pjreddie/darknet/issues/1401

**Comment by nightfuryyy** [comment]
thank u for helping me
