### ISSUE TITLE
InvalidArgumentError: Incompatible shapes

### ISSUE THREAD

**Issue by AnikaP** [wizyoung/YOLOv3_TensorFlow#112]
Hey, 
my training stops immediately after the following error:

> `2019-07-09 08:36:12.220852: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-07-09 08:36:13.081077: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:03:00.0
> totalMemory: 10.91GiB freeMemory: 10.76GiB
> 2019-07-09 08:36:13.241345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties:
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:04:00.0
> totalMemory: 10.92GiB freeMemory: 10.76GiB
> 2019-07-09 08:36:13.242391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
> 2019-07-09 08:36:13.821277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-07-09 08:36:13.821313: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1
> 2019-07-09 08:36:13.821321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N Y
> 2019-07-09 08:36:13.821325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   Y N
> 2019-07-09 08:36:13.821749: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10407 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
> 2019-07-09 08:36:13.822072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10409 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1)
> INFO:tensorflow:Restoring parameters from ./data/darknet_weights/yolov3.ckpt
>   0%|          | 0/244 [00:00<?, ?it/s]Saving optimizer parameters to checkpoint! Remember to restore the global_step in the fine-tuning afterwards.
> 
> ----------- start to train -----------
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
>     return fn(*args)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [4,19,35,3,1] vs. [4,18,34,3,1]
> 	 [[{{node logistic_loss/mul}} = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](split:2, strided_slice_137)]]
> 	 [[{{node concat_18/_825}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_59264_concat_18", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "train.py", line 140, in <module>
>     feed_dict={is_training: True})
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
>     run_metadata)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [4,19,35,3,1] vs. [4,18,34,3,1]
> 	 [[node logistic_loss/mul (defined at /home/anika/YOLOv3_TensorFlow/model.py:282)  = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](split:2, strided_slice_137)]]
> 	 [[{{node concat_18/_825}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_59264_concat_18", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> 
> Caused by op 'logistic_loss/mul', defined at:
>   File "train.py", line 75, in <module>
>     loss = yolo_model.compute_loss(pred_feature_maps, y_true)
>   File "/home/anika/YOLOv3_TensorFlow/model.py", line 359, in compute_loss
>     result = self.loss_layer(y_pred[i], y_true[i], anchor_group[i])
>   File "/home/anika/YOLOv3_TensorFlow/model.py", line 282, in loss_layer
>     conf_loss_pos = conf_pos_mask * tf.nn.sigmoid_cross_entropy_with_logits(labels=object_mask, logits=pred_conf_logits)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_impl.py", line 181, in sigmoid_cross_entropy_with_logits
>     relu_logits - logits * labels,
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 866, in binary_op_wrapper
>     return func(x, y, name=name)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 1131, in _mul_dispatch
>     return gen_math_ops.mul(x, y, name=name)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 5042, in mul
>     "Mul", x=x, y=y, name=name)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
>     op_def=op_def)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> InvalidArgumentError (see above for traceback): Incompatible shapes: [4,19,35,3,1] vs. [4,18,34,3,1]
> 	 [[node logistic_loss/mul (defined at /home/anika/YOLOv3_TensorFlow/model.py:282)  = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](split:2, strided_slice_137)]]
> 	 [[{{node concat_18/_825}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_59264_concat_18", tensor_type=DT_FL`

I already trained some Tensorflow models (Yolo, Faster RCNN) with my data. Any Idea what I am doing wrong here? I used your args.py and just set the batch size to 4 and adjusted the data paths.

**Comment by AnikaP** [comment]
So I forgot that I increased the image size to 600x600. This seems to be the issue... Anyway, I would like to train with bigger images, is there anything I need to adjust when changing the size?

**Comment by wizyoung** [comment]
you should make sure that the image size can be divided by 32.

**Comment by AnikaP** [comment]
Thanks!

**Comment by iampalop** [comment]
> you should make sure that the image size can be divided by 32.

why the image size can be divided by 32.
explain, please

**Comment by AhmedAnwar97** [comment]
@iampalop @wizyoung 
does this have an explanation?

**Comment by iampalop** [comment]
@AhmedAnwar97  
I think because feature map dimension is 32x32
can you explain it to me?

**Comment by AhmedAnwar97** [comment]
@iampalop 
Check issue #247 ... LyuYifan illustrated the reasons of this issue.
