### ISSUE TITLE
The error for train about IndexError

### ISSUE THREAD

**Issue by lyzinfo** [wizyoung/YOLOv3_TensorFlow#115]
I get a training error as shown below

----------- start to train -----------

 24%|██████████                               | 100/410 [00:31<00:44,  6.95it/s]Traceback (most recent call last):
  File "train.py", line 152, in <module>
    recall, precision = evaluate_on_gpu(sess, gpu_nms_op, pred_boxes_flag, pred_scores_flag, __y_pred, __y_true, args.class_num, args.nms_threshold)
  File "/emc_lun/lyz/mammo/YOLOv3_TensorFlow-master/utils/eval_utils.py", line 180, in evaluate_on_gpu
    box_centers, box_sizes = true_boxes[:, 0:2], true_boxes[:, 2:4]
IndexError: too many indices for array

What can be the problem for this error?

**Comment by wizyoung** [comment]
Make a search for current solved issues before raising a new issue.
refer to https://github.com/wizyoung/YOLOv3_TensorFlow/issues/64
