### ISSUE TITLE
what is precision?

### ISSUE THREAD

**Issue by rybkaa** [wizyoung/YOLOv3_TensorFlow#116]
when i train i get high mAP but low precision, so what is precision and how much does it really matter when using the model?

**Comment by yanjishuang** [comment]
I have encountered the same problem as you. Have you solved it？

**Comment by wizyoung** [comment]
Because the score threshold is small. For higher mAP, you should set score_threshold to a small number like 0.001. But for real practice, choose bigger number like 0.3 is better. For more information about mAP, I think google it is better.
