### ISSUE TITLE
IndexError: index 505 is out of bounds for axis 3 with size 11，有处代码您写的有问题，望指正

### ISSUE THREAD

**Issue by panlanlan** [wizyoung/YOLOv3_TensorFlow#117]
作者您好，经过对您的代码进行验证，发现了一个错误，我不知道是不是这样子，在data_utils.py中有一行代码parse_line(line)这个函数中    
if 'str' not in str(type(line)):
        line = line.decode()
    s = line.strip().split(' ')
    line_idx = int(s[0])
    pic_path = s[1]
    s = s[2:]  
中此处s不应该是 s = s[2:]而是s[4:]，这样才能取到对应的参数值，否则会报错，越界问题，望您能够验证，这个问题是不是存在

**Comment by wizyoung** [comment]
You are reading an old version of my code.

**Comment by panlanlan** [comment]
是的，我是很早下载的，后面看到你更新的版本 已经更正过来了，能否请作者您，好好整理下代码结构，感觉代码整体结构很乱，对于我这种小白，只有一行行调试，才看的明白

**Comment by wizyoung** [comment]
请问代码结构哪里乱了
