### ISSUE TITLE
训练保存的ckpt模型比较大

### ISSUE THREAD

**Issue by nobody-cheng** [wizyoung/YOLOv3_TensorFlow#120]
请问下为什么训练保存的模型会大这么多，按理来说网络结构又没有做出多大修改， 权重大小应该差不多才对

**Comment by wizyoung** [comment]
默认保存了优化器的参数，方便后续接着训，以 adam 为例，保存的模型权重会是原始模型的3倍大。测试阶段不需要这些优化器参数，可以用我在 misc 下提供的脚本剔除掉。

**Comment by nobody-cheng** [comment]
> 默认保存了优化器的参数，方便后续接着训，以 adam 为例，保存的模型权重会是原始模型的3倍大。测试阶段不需要这些优化器参数，可以用我在 misc 下提供的脚本剔除掉。

多谢，已解决
