### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by smoolya17** [wizyoung/YOLOv3_TensorFlow#123]
When I train my model i get the following error:

`
    

>   ----------- start to train -----------

       0%|                                                                                                             | 0/2 [00:00<?, ? 
       it/s]2019-07-30 21:04:50.707059: W tensorflow/core/framework/op_kernel.cc:1490] 
       Unknown: AttributeError: 'NoneType' object has no attribute 'shape'
       Traceback (most recent call last):

       File "/mnt/c/yolov3_setup/myobjectv3_ubuntu/lib/python3.7/site- 
    packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
       ret = func(*args)

    File "/mnt/c/yolov3_setup/YOLOv3_TensorFlow/utils/data_utils.py", line 214, in get_batch_data
      img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, 
    mode, letterbox_resize)

    File "/mnt/c/yolov3_setup/YOLOv3_TensorFlow/utils/data_utils.py", line 167, in parse_data
      img, boxes = resize_with_bbox(img, boxes, img_size[0], img_size[1], interp=1, 
    letterbox=letterbox_resize)

    File "/mnt/c/yolov3_setup/YOLOv3_TensorFlow/utils/data_aug.py", line 302, in 
    resize_with_bbox
      image_padded, resize_ratio, dw, dh = letterbox_resize(img, new_width, new_height, interp)

    File "/mnt/c/yolov3_setup/YOLOv3_TensorFlow/utils/data_aug.py", line 278, in letterbox_resize
      ori_height, ori_width = img.shape[:2]

     AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by wizyoung** [comment]
Your data is not clean. Maybe the image path is not valid.

**Comment by smoolya17** [comment]
I have cross checked the image path already. Also my image data is of size 448*448. What do we mean here by clean data?

**Comment by smoolya17** [comment]
I will cross check again once I resume

**Comment by smoolya17** [comment]
I am using ubuntu app in windows 10 desktop for training.
So in my `train.txt` my absolute path is set to `/mnt/c/yolov3_setup/YOLOv3_TensorFlow/data/my_data/Bank_Proof/jpg_resized/TE906084_Bank_Proof~2_resized.jpg`

Image path seems valid. What else could be the problem?

**Comment by smoolya17** [comment]
Yes the data input `'train.txt'` & `'val.txt'` was faulty. I used `misc/parse_voc_xml.py` then to build my train.txt & val.txt & resolved the error.

**Comment by 1995gatch** [comment]
> Yes the data input `'train.txt'` & `'val.txt'` was faulty. I used `misc/parse_voc_xml.py` then to build my train.txt & val.txt & resolved the error.

Hello, can you solve the problem by running misc/parse_voc_xml.py directly？
