### ISSUE TITLE
No bounding box in the output

### ISSUE THREAD

**Issue by smoolya17** [wizyoung/YOLOv3_TensorFlow#129]
I have trained the yolov3 network with 1 class and got mAP of 91.67% . Following are the specifics related to training:
1. score_threshold:0.005
2. cpu trained
3. Number of training samples:52
4. Number of Evaluation Samples:3

When I execute `python test_single_image_\(copy\).py ./data/my_data/Bank_Proof/test/TE922428_Bank_Proof~2.jpg ` I get the image with **NO** bounding boxes drawn around the object. Why is it so?

**Comment by wizyoung** [comment]
Check the parameters carefully. Parameters need to be same in both train.py and test_single_image.py.

**Comment by smoolya17** [comment]
@wizyonung I will check it once again
Especially which parameter are you referring to?

**Comment by smoolya17** [comment]
@wizyoung   So the train.py --restore didn't match the 'test_single_image.py' value.
Why are the two files interdependent ?
