### ISSUE TITLE
Error when running background via nohup

### ISSUE THREAD

**Issue by ahmedselim2017** [wizyoung/YOLOv3_TensorFlow#131]
When I run `nohup CUDA_VISIBLE_DEVICES=GPU_ID python train.py &` it gives `nohup: failed to run the command 'CUDA_VISIBLE_DEVICES=GPU_ID': No such file or directory` error.

**Comment by ahmedselim2017** [comment]
OK, I got it. Because `CUDA_VISIBLE_DEVICES=GPU_ID` a variable declaration, it has to be declared outside of nohup. So the solution was first declaring it and then running `nohup python train.py`.

**Comment by rksamal-bh** [comment]
HOW will you implement outside nohup can i know

**Comment by shuyijia** [comment]
> 

`CUDA_VISIBLE_DEVICES=1 nohup python test.py > test.out &`
