### ISSUE TITLE
How to use my dataset trained weight ?

### ISSUE THREAD

**Issue by iampalop** [wizyoung/YOLOv3_TensorFlow#133]

**Comment by smoolya17** [comment]
If you can elaborate we can try helping

**Comment by iampalop** [comment]
I've already got it, thx

**Comment by aluds123** [comment]
@iampalop 
Hi, I have some question want to ask you.
If I want to train my own data, how should I do on args.py (restore_path).
Thanks

**Comment by iampalop** [comment]
just do step 3.Weights convertion
![image](https://user-images.githubusercontent.com/23123640/69434741-c91f6e80-0d70-11ea-9843-8414034ae468.png)

**Comment by iampalop** [comment]
do 3.Weights convertion
![image](https://user-images.githubusercontent.com/23123640/69434954-3d5a1200-0d71-11ea-9eed-ef082bf724a4.png)

**Comment by iampalop** [comment]
replace with ./checkpoint/your trained model in checkpoint folder'
ex
./checkpoint/model-epoch_xx_step_xxxxx_loss_x.xxxx_lr_xxxxx'

**Comment by aluds123** [comment]
@iampalop 
Thanks for your help, but I still have some question.
![擷取1](https://user-images.githubusercontent.com/43241182/69488317-c3c24100-0ea2-11ea-8084-2f73dc9a5610.PNG)
Do you mean like the image above?

But before I train it, I have nothing in './checkpoint'.
Can you guide me how to train my own data? (I already prepare the pictures and labels for 6 class)

Thanks

**Comment by iampalop** [comment]
@aluds123 
try this
restore_path = '/home/aluds/quantize_test/checkpoint/best_model_Epoch_100_step_94636_mAP_0.0975_loss_42.8298_lr_0.0001'
with out '.data-xxxxx-of-xxxxx'

**Comment by aluds123** [comment]
@iampalop 
Thanks for your help.
I will try it later.

**Comment by ongspxm** [comment]
i managed to train the model, but when i tried to run it using the `restore_path`, i seem to have the following issue that says that the model is of the wrong size, is it not saving right?

```
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,1
024,255] rhs shape= [1,1,1024,21]
         [[Node: save/Assign_350 = Assign[T=DT_FLOAT, _class=["loc:@yolov3/yolov3_head/Conv_6/weights"], use_locki
ng=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](yolov3/yolov3_head/Conv_6/we
ights, save/RestoreV2/_151)]]
```

**Comment by aluds123** [comment]
> i managed to train the model, but when i tried to run it using the `restore_path`, i seem to have the following issue that says that the model is of the wrong size, is it not saving right? @lampalop
> 
> ```
> InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,1
> 024,255] rhs shape= [1,1,1024,21]
>          [[Node: save/Assign_350 = Assign[T=DT_FLOAT, _class=["loc:@yolov3/yolov3_head/Conv_6/weights"], use_locki
> ng=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](yolov3/yolov3_head/Conv_6/we
> ights, save/RestoreV2/_151)]]
> ```

@ongspxm 
What the model do u use?

**Comment by ongspxm** [comment]
oh hi, i resolved it, i went through the layers and found that the layer
size changes because the image size is not updated when I was running the
test_single_image. After i change the img size, everything works :+1:

**Comment by iampalop** [comment]
@aluds123 
image size must can divide by 32

**Comment by FrodoLuo** [comment]
@ongspxm 
Would you please tell me how do you change img's size? Or where the code did you modified?

**Comment by ongspxm** [comment]
https://github.com/wizyoung/YOLOv3_TensorFlow/blob/c8c40615e0cdf00deea065fc89c3e93909c1a88a/args.py#L21
