### ISSUE TITLE
关于x1,y1,x2,y2的疑问

### ISSUE THREAD

**Issue by LiweiDai** [wizyoung/YOLOv3_TensorFlow#137]

**Comment by LiweiDai** [comment]
而且最近我在调用你的cpu_nms的时候，会报错，我不清楚这段代码是被弃用了还是没有进行维护更新？请指教哦~~

**Comment by LiweiDai** [comment]
train的时候，是有cpu和gpu版的nms可选，而进行eval和test的时候只能用gpu的nms，没有cpu~

**Comment by wizyoung** [comment]
CPU的因为我自己几乎不用，所以暂时没维护。最近太忙，周末我抽空看看

**Comment by LiweiDai** [comment]
嗯，辛苦了，我今天在你这个框架下弄softnms，用py_func搞得，在gpu上跑成功了，但是检测结果和默认nms差好多，前者52map，后者75，我等下改下代码，要找找为啥差这么多了，按理说不应该啊，哎。你去看看x和y那里，tf注释和你不一致，但是结果没问题，奇怪了哈哈



---原始邮件---
发件人: "Wizyoung"<notifications@github.com>
发送时间: 2019年8月23日(星期五) 下午4:03
收件人: "wizyoung/YOLOv3_TensorFlow"<YOLOv3_TensorFlow@noreply.github.com>;
抄送: "dailiwei"<3376321599@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wizyoung/YOLOv3_TensorFlow] 关于x1,y1,x2,y2的疑问 (#137)



CPU的因为我自己几乎不用，所以暂时没维护。最近太忙，周末我抽空看看

**Comment by LiweiDai** [comment]
今晚的成果，实现了pyfunc操作的能在gpu上跑的softnms，也出现了一个疑点，用这个自己写的接口时，传统nms结果和tf的api结果一致，但gaussian和linear，结果和常规nms掉了近20mAP，recall却提升了3个点，作者兄弟你觉得这个正常吗?
gaussian和linear下，我的iou_threah=0.3，sigma=0.5，按照论文实验的。
常规nms参数iou_thresh是0.5。
linear和gaussian结果接近，mAP都低。

---原始邮件---
发件人: "Wizyoung"<notifications@github.com>
发送时间: 2019年8月23日(星期五) 下午4:03
收件人: "wizyoung/YOLOv3_TensorFlow"<YOLOv3_TensorFlow@noreply.github.com>;
抄送: "dailiwei"<3376321599@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wizyoung/YOLOv3_TensorFlow] 关于x1,y1,x2,y2的疑问 (#137)



CPU的因为我自己几乎不用，所以暂时没维护。最近太忙，周末我抽空看看

**Comment by LiweiDai** [comment]
看来真的是yolo不适合soft，v3尤其严重，不升反降。

**Comment by LiweiDai** [comment]
> CPU的因为我自己几乎不用，所以暂时没维护。最近太忙，周末我抽空看看

此外代码有一处不合理的代码，就是在不使用warm up时候，warm up epoch应该抑制为0，但是目前的没有，我添加了一个语句解决了，但是小白在使用的时候，默认前3轮是不会保存ckpt的，虽然这三轮没必要。

**Comment by LiweiDai** [comment]
wizyoung你好，麻烦把这条issue删了吧，内容被我清除了，属于无关的comment，其中的问题我这边屡清楚了，麻烦删除一下~

**Comment by LiweiDai** [comment]
hi, maybe it's better to delete this issue, cause i have delete allllll the comments in it, ahaha~~~thx!
