### ISSUE TITLE
eval的结果数值好像有点不对

### ISSUE THREAD

**Issue by shm007g** [wizyoung/YOLOv3_TensorFlow#142]
```
EVAL: Class 0: Recall: 0.8966, Precision: 0.0568, AP: 0.7949
EVAL: Recall: 0.8966, Precison: 0.0568, mAP: 0.7949
EVAL: loss: total: 4.69, xy: 0.28, wh: 0.42, conf: 3.97, class: 0.01
```

precision一直都在个位数百分点

**Comment by chen3718** [comment]
@shm007g 
EVAL: Class 0: Recall: 0.9305, Precision: 0.0205, AP: 0.7364
EVAL: Recall: 0.9305, Precison: 0.0205, mAP: 0.7364
EVAL: loss: total: 0.88, xy: 0.11, wh: 0.06, conf: 0.71, class: 0.00

我这边也是，请问有发现原因吗？ 单分类

**Comment by jpff96** [comment]
I think this issue is related to #152

**Comment by chen3718** [comment]
@jpff96  thanks! Is it okay to change it to 2 for single class detection?

**Comment by jpff96** [comment]
I am not sure about the right number but I trained a model for single class detection and change this value to 1 or 2 the precision and recall raise 0.65 - 0.6
