### ISSUE TITLE
About the func evaluate_on_gpu, 

### ISSUE THREAD

**Issue by rainley123** [wizyoung/YOLOv3_TensorFlow#15]
when I run the func evaluate_on_gpu, why it is soooooooooo slow???

**Comment by wizyoung** [comment]
How's your speed? What's your running env? Have you checked the output of `nvidia-smi` when running?

**Comment by rainley123** [comment]
I find it is because the funtion:gpu_nms(), I have solved this problem, but I can't understand it.
Here is the code in your respority:
pred_boxes, pred_confs, pred_labels = sess.run(gpu_nms_op,
                                                       feed_dict={pred_boxes_flag: pred_boxes,
                                                                  pred_scores_flag: pred_confs * pred_probs})
and in the train.py, you feed the data for gpu_nms_op.
I have changed the code as follow:
pred_boxes, pred_confs, pred_labels = nms_utils.nms(sess, pred_boxes, pred_confs*pred_probs, num_classes, score_thresh=score_thresh, iou_thresh=iou_thresh)
and in gpu_nms() func, I use boxes_, score_, label_ = sess.run([boxes, score, label]) to get the array variables: boxes_, score_, label_. Use this method, the code will run very slow.
So why it run faster when the gpu_nms_op() is defined in train.py using feed_dict, 
why it run sooooo slow when I give a sess to the gpu_nms() to get variables(should return array not a tensor)

**Comment by wizyoung** [comment]
Because TensorFlow is graph based. Everything like setting up the ops should be finished before actual running. Once starting the session, you should not add more ops as it will pause to update the graph and it's slow! And it may cause OOM problems as the ops are added in every step. That's why I define a gpu_nms_op before the session.

**Comment by rainley123** [comment]
> session
Thanks for your answer! have you ever train VOC data by your model?

**Comment by wizyoung** [comment]
Not yet. Because I am really busy these days and have no time to train it on VOC dataset. If you do that, please add data augmentation and other tricks in the readme file.

**Comment by wizyoung** [comment]
@rainley123 I have made quick tests on the VOC dataset. Performance is good. Refer to comments here: https://github.com/wizyoung/YOLOv3_TensorFlow/pull/93
