### ISSUE TITLE
"ignore_mask" should be added to "conf_pos_mask" rather than "conf_neg_mask"

### ISSUE THREAD

**Issue by bitgs** [wizyoung/YOLOv3_TensorFlow#164]
Hello "big god",

A question about "ignore_mask":

The effect of "ignore_mask" is putting "1" in locations where the IOUs between bounding box priors and ground truth boxes are less than 0.5. Hence, by multiplying this "ignore_mask" with "(1 - object_mask)" will lead to exactly the same result as solely using "(1 - object_mask)" without multiplying "ignore_mask". Because this "ignore_mask" will always be looser than "(1 - object_mask)".

**Comment by bitgs** [comment]
Got the answer, you implement is perfect
O(∩_∩)O哈哈~

**Comment by zyc4me** [comment]
@bitgs hi ，  i have a problem,can you help me?  
 i use the ./misc/experiments_on_voc/args_voc.py to train  VOC07+12, bug i can not get 87.xx map, is only 84 map, and the xy_loss, wh_loss, conf_loss and class_loss are very small , like  0.02  0.03  0.01 0.35, but this four loss in val is very big, like  0.37  0.40  4.55, 1.11
