### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by madhu-korada** [wizyoung/YOLOv3_TensorFlow#17]
I am training with custom data which looks like this.
img size is 720*1280
my training data looks like this

![image](https://user-images.githubusercontent.com/36992005/53547934-545b3300-3b56-11e9-8aa1-2714b6f4f7dc.png)
Training is not starting and
i am getting an error like this

OutOfRangeError: End of sequence
	 [[node IteratorGetNext (defined at C:/Users/madhu/Desktop/YOLOv3_TensorFlow-master/train.py:160)  = IteratorGetNext[output_shapes=[<unknown>, <unknown>, <unknown>, <unknown>], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorFromStringHandleV2)]]
	 [[{{node IteratorGetNext/_535}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_671_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

please help me resolve this issue

**Comment by meet-minimalist** [comment]
I am also getting the same error with default size of 416x416.

**Comment by wizyoung** [comment]
can you try python2 to check it again?

**Comment by meet-minimalist** [comment]
@wizyoung @madhu-korada 
I have solved the problem. Actually problem is in utils/data_utils.py line no. 19. I have added following 2 lines above that. 

line = str(line)
line = line[2:len(line)-2]


Basically parse_line(line) function works well when we directly feed it with text line through python as the "str" type is passed. But when we use it inside tf.py_func() then it passes "bytes" which needs to be converted to "str" and preprocessed a bit.

**Comment by wizyoung** [comment]
@meet-minimalist Thanks for your work! The problem seems to lie in the difference between the encoding-decoding mechanism between Python2 and Python3. I'm using Python2 and there is no "bytes" in Python2.

**Comment by madhu-korada** [comment]
@meet-minimalist @wizyoung I have checked all the  My data formatting is correct and working fine and i don't think python compatibility problem is there. I am not  able to find the problem, i will update the progress.

**Comment by madhu-korada** [comment]
And one more thing if my input image size is 720*1280, it would be possible because 720 is not divisible by 32. i cropped image to 704*1280. 

Still the error i mentioned above hasn't resolved.

**Comment by meet-minimalist** [comment]
@wizyoung 
That remove 2 characters from the start of the string and last 2 characters of the string. 

Because the string we pass is starts with <b'>. And ends with <'\n'>. So to remove these 2 characters from both ends I have used it.

**Comment by wizyoung** [comment]
@meet-minimalist Thanks. That really helps.
