### ISSUE TITLE
About precision and recall

### ISSUE THREAD

**Issue by rainley123** [wizyoung/YOLOv3_TensorFlow#18]
I have a question about the precision and recall.I have trained model on voc2007, and the precision and recall can get 90%+ during training, but when I run on the eval dataset, the precision is 80%, more Important is that the recall is only 30%!!!!!! , what can i do to improve the precision especially recall!!!

**Comment by wizyoung** [comment]
Add data augmentation.

**Comment by rainley123** [comment]
I have already added data augmentation: filp_left_right, flip_up_down, random_crop, random distord color

**Comment by rainley123** [comment]
我在训练voc数据集的时候碰到两种情况，第一种训练的时候loss收敛在7左右，precision和racall分别在0.8和0.7左右，但是验证集的loss反而小于1，precision和recall为0.75和0.55。第二种情况是train的loss在0.7左右，precision和recall能达到0.95以上，然而验证集的loss就在5左右，precision能到0.8，但是recall只有0.3！！这种情况下 我还看了一下各个类的precision和recall情况，发现有几类物体的recall就特别低

**Comment by wizyoung** [comment]
That's far from enough. Refer to https://github.com/dmlc/gluon-cv/tree/master/scripts/detection/yolo. for more detailed data augmentation.
And you may also consider the data unbalance problem related to the dataset. Training strategy is critical to object detection task. These days I'm busy and have no time to maintain this repo. This repo should be a reference to people who want to dive into YOLO-v3 rather than take it and use it without modification.

**Comment by wizyoung** [comment]
There's is a repo (https://github.com/Stinky-Tofu/Stronger-yolo) which has added many sota training skills to yolov3. You can check the difference. I'll update this project in a few months later due to the lack of time.

**Comment by rainley123** [comment]
> That's far from enough. Refer to https://github.com/dmlc/gluon-cv/tree/master/scripts/detection/yolo. for more detailed data augmentation.
> And you may also consider the data unbalance problem related to the dataset. Training strategy is critical to object detection task. These days I'm busy and have no time to maintain this repo. This repo should be a reference to people who want to dive into YOLO-v3 rather than take it and use it without modification.
Sorry, I can't find the data augmentation in https://github.com/dmlc/gluon-cv/tree/master/scripts/detection/yolo
