### ISSUE TITLE
about convert_weights

### ISSUE THREAD

**Issue by ClayZhang0403** [wizyoung/YOLOv3_TensorFlow#19]
hello wizyoung， when i run the python convert_weights.py  ， it happend following errors：
Traceback (most recent call last):  File "convert_weight.py", line 30,  File"D:\ocr\YOLOv3_TensorFlow\utils\misc_utils.py", line 101, in load_weights     (shape[3], shape[2], shape[0], shape[1]))                                   
 ValueError: cannot reshape array of size 285787 into shape (256,128,3,3)
what should i do ？ thx

**Comment by zzflybird** [comment]
I have the same problem. It has been bothering me for a long time. Can someone help me?
![image](https://user-images.githubusercontent.com/26504661/56452014-182b9e00-6361-11e9-9666-8c9124bf8138.png)

**Comment by ggolkar** [comment]
Hi ,
 I modified the darknet-body and trained it with Darknet to get the weight . When I use the weight and  run the python convert_weights.py.I get the same error mentioned above .
 File "C:\Users\Desktop\YOLOv3_TensorFlow-master\utils\misc_utils.py", line 124, in load_weights
    (shape[3], shape[2], shape[0], shape[1]))
ValueError: cannot reshape array of size 264248 into shape (256,128,3,3)

Could you please help me with this ?
Thanks .

**Comment by wizyoung** [comment]
I think this is weird. Maybe weights file gets corrupted? You can use my converted weight file here:https://github.com/wizyoung/YOLOv3_TensorFlow/releases

**Comment by uningsun** [comment]
I think editing this code's number causes ValueError. 
```model = yolov3(80, anchors)```
I modified ```num_class = 80``` to ```num_class = 196 # my dataset```. When I noticed ```model = yolov3(80, anchors)```, I changed 80 to 196, but I got ValueError.
So I changed again 196 to 80, then I got new .ckpt file.
