### ISSUE TITLE
【Python3】数据增强没有启用

### ISSUE THREAD

**Issue by wenfenglin** [wizyoung/YOLOv3_TensorFlow#200]
感谢作者的分享，我在使用过程中发现一个问题（Python3.7，Tensorflow1.14）：

https://github.com/wizyoung/YOLOv3_TensorFlow/blob/c8c40615e0cdf00deea065fc89c3e93909c1a88a/train.py#L38
如上，数据预处理是通过py_func调用的，而使用Python3时py_func会把字符串（mode的值）转为bytes，导致
https://github.com/wizyoung/YOLOv3_TensorFlow/blob/c8c40615e0cdf00deea065fc89c3e93909c1a88a/utils/data_utils.py#L143
这个条件判断结果永远都是False（‘train’ != b'train'）。建议将参数mode改为布尔型。

**Comment by wizyoung** [comment]
是的，这里应该改成 bool 型判定比较好，我用的 python2 不知道有这个问题，感谢告知

**Comment by pgirikishore** [comment]
What are we supposed to do?

**Comment by aaron38** [comment]
In `data_utils.py` change every `mode == 'train'` to `mode` (Lines 143, 194 and 203). 
Then, change the input argument `'train'` to `True`, and `'val'` to `False` every time `get_batch_data` is used (in `eval.py`, `train.py`, `eval_voc.py`).
This should work.
(Personally, I would rename the variable 'mode' to something like 'train_mode' for better readability)

**Comment by pgirikishore** [comment]
Thanks a lot

**Comment by guodata** [comment]
加一句mode = str(mode) 在get_batch_data函数即可吧

**Comment by liuzaozao7799** [comment]
> 加一句mode = str(mode) 在get_batch_data函数即可吧

感谢您的意见！我这里测试了一下，对于我的机器需要加编码说明才能转换成功
`mode = str(mode, encoding = "utf-8")`

**Comment by cxjaicj** [comment]
> 是的，这里应该改成 bool 型判定比较好，我用的 python2 不知道有这个问题，感谢告知

您好  感谢您提供的YOLOV3仓库，但是不知道什么原因，您提供的VOC数据集权重下载链接我无法使用，能否私发一份权重。万分感谢 QQ 1552005123

**Comment by wizyoung** [comment]
fixed
