### ISSUE TITLE
Training process suddenly diverges，help

### ISSUE THREAD

**Issue by chaowentao** [wizyoung/YOLOv3_TensorFlow#23]
![image](https://user-images.githubusercontent.com/37093663/54064899-0e882400-4254-11e9-925e-91ff70b4258d.png)
I am training in my own dataset.Follow the documentation exactly.
The last time the output was normal, the next time it was nan.
Help,please.

**Comment by wizyoung** [comment]
Duplicate with [#3](https://github.com/wizyoung/YOLOv3_TensorFlow/issues/3).
