### ISSUE TITLE
output_node_names

### ISSUE THREAD

**Issue by FelixWeichselgartner** [wizyoung/YOLOv3_TensorFlow#231]
Hi,

i want to freeze my model, which i trained with your repo.
Therefore i wanted to use this script (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py) similar to (https://github.com/YunYang1994/tensorflow-yolov3/blob/master/freeze_graph.py) in your sources.

However im missing the output_node_names, which i couldnt find in issues or in the repo.
Has anybody successfully converted a model trained by this repo to pb yet?

My goal is to use my trained model in OpenCV (https://docs.opencv.org/master/da/d9d/tutorial_dnn_yolo.html).

Any help is appreciated. Thank you all.

Greetings
Felix Weichselgartner

**Comment by ucas010** [comment]
hi,dear,
have the same problem too,
and then what's the input_data node name?

**Comment by FelixWeichselgartner** [comment]
just use this repo: https://github.com/AlexeyAB/darknet
its forked from the original darknet
this has way better documentation and exports models as weights file -> therefore you can easily import it in opencv_dnn or sth similar without knowing the nodes.
hf worked for me

**Comment by alphapibeta** [comment]
> just use this repo: https://github.com/AlexeyAB/darknet
> its forked from the original darknet
> this has way better documentation and exports models as weights file -> therefore you can easily import it in opencv_dnn or sth similar without knowing the nodes.
> hf worked for me

Hello can you please help me in converting the checkpoint to a .pb file
if you can share what steps did you follow, that will be grateful.

**Comment by alexanderDuenas** [comment]
Hi, I have the same problem, some solution?
