### ISSUE TITLE
convert yolov3-tiny

### ISSUE THREAD

**Issue by SouradipBh** [wizyoung/YOLOv3_TensorFlow#233]
i want to convert custom yolov3-tiny.weghts file.

Can any help me with this?

**Comment by qawsedrg** [comment]
you may refer to https://github.com/qawsedrg/yolov3_yolov4_tensorflow i have add yolo tiny as well as yolov4 support within the training frame work of this repo.

**Comment by SouradipBh** [comment]
> you may refer to https://github.com/qawsedrg/yolov3_yolov4_tensorflow i have add yolo tiny as well as yolov4 support within the training frame work of this repo.

Thanks @qawsedrg
