### ISSUE TITLE
typeError: map_and_batch() got an unexpected keyword argument 'num_parallel_calls

### ISSUE THREAD

**Issue by jamiechoi1995** [wizyoung/YOLOv3_TensorFlow#25]
I got the above error when I start training,

however, when I remove `num_parallel_calls=args.num_threads,` in https://github.com/wizyoung/YOLOv3_TensorFlow/blob/2f61e5bca30179aecdab1e9c2870df31ab1021df/train.py#L139, it works

**Comment by wizyoung** [comment]
I guess it was caused by the API change of tensorflow and `num_parallel_calls` just changed to another name. So what's your version of tensorflow?

**Comment by jamiechoi1995** [comment]
@wizyoung 1.8.0

**Comment by wizyoung** [comment]
See [here](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/contrib/data/python/ops/batching.py#L436), change `num_parallel_calls` to `num_parallel_batches`.

**Comment by jamiechoi1995** [comment]
@wizyoung 
I think `num_parallel_calls` and `num_parallel_batches` are different, especially in the higher version of  tensorflow, see: https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/contrib/data/python/ops/batching.py#L436

may I ask what's your version of tensorflow?

**Comment by wizyoung** [comment]
@jamiechoi1995 Oh, they are different. I'm using tf 1.9.0 (python2) myself on ubuntu. You can split this function to `map` and `batch` which I think is OK. I'm using this function as I want to eliminate the time delay between `map` and `batch` ops according to the tensorflow performance guide.
