### ISSUE TITLE
where is video_result.mp4 ?  when I python video_test.py ./data/demo_data/vedio.mp4

### ISSUE THREAD

**Issue by dingxihao1991** [wizyoung/YOLOv3_TensorFlow#26]
where is video_result.mp4 ?  when I python video_test.py ./data/demo_data/vedio.mp4

**Comment by wizyoung** [comment]
Videos will not be saved by default. You should set `save_video` flag to `True` to do that. Check the code [here](https://github.com/wizyoung/YOLOv3_TensorFlow/blob/master/video_test.py#L28).
