### ISSUE TITLE
Question about resizing the anchor

### ISSUE THREAD

**Issue by jamiechoi1995** [wizyoung/YOLOv3_TensorFlow#27]
I noticed that you mention in README.md that

> NOTE: The yolo anchors should be scaled to the rescaled new image size. Suppose your image size is [W, H], and the image will be rescale to 416*416 as input, for each generated anchor [anchor_w, anchor_h], you should apply the transformation anchor_w = anchor_w / W * 416, anchor_h = anchor_g / H * 416.

however, the size of the images in my dataset are varied, do I need to calculate the mean H and W of my images and apply the above transformation?

**Comment by jamiechoi1995** [comment]
Or should I apply the transformation first, before the k-means process?

**Comment by zzflybird** [comment]
I have the same problem. My pictures are in the following formats: 6016*4016 6000*4000 4608*2592 4288*2848 2000*1330
Do I need to preprocess the image into a uniform format? Or can we just average the anchor_w and anchor_h from multiple image formats?

**Comment by wizyoung** [comment]
resize the anchor to your input image scale. Applying the transformation before or afterwards are both ok
