### ISSUE TITLE
Question about the prepared data

### ISSUE THREAD

**Issue by dunaizhuan** [wizyoung/YOLOv3_TensorFlow#28]
Should i transform the origin images' bx,by,bw,bh ?
e.g. if my image is 213*213  bx =1 by = 1, i should transform the image to 416*416 and replace bx = 2 . and put the transformed image's path and bx,by,bh,bw in data.txt ?

**Comment by dunaizhuan** [comment]
2019-03-17 13:48:00.646657: W tensorflow/core/framework/op_kernel.cc:1261] Invalid argument: TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):

  File "H:\py\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "D:\futurelab\yolo\utils\data_utils.py", line 130, in parse_data
    pic_path, boxes, labels = parse_line(line)

  File "D:\futurelab\yolo\utils\data_utils.py", line 19, in parse_line
    s = line.strip().split(' ')

TypeError: a bytes-like object is required, not 'str'

**Comment by AleXander-Tsui** [comment]
@dunaizhuan 你可以参考一下[#17](https://github.com/wizyoung/YOLOv3_TensorFlow/issues/17)，这是因为python2和python3的区别所导致的

**Comment by dunaizhuan** [comment]
> @dunaizhuan 你可以参考一下[#17](https://github.com/wizyoung/YOLOv3_TensorFlow/issues/17)，这是因为python2和python3的区别所导致的

解决了 可是这是怎么回事 loss很低了 但是准确率和召回为0？

![ER_%8%7BRBD26 LJB7HC19](https://user-images.githubusercontent.com/40169984/54572533-f9b14a80-4a22-11e9-808e-328c6a2b6487.png)

**Comment by dunaizhuan** [comment]
> @dunaizhuan 你可以参考一下[#17](https://github.com/wizyoung/YOLOv3_TensorFlow/issues/17)，这是因为python2和python3的区别所导致的

谢谢了

**Comment by AleXander-Tsui** [comment]
> 解决了 可是这是怎么回事 loss很低了 但是准确率和召回为0？
> 
> ![ER_%8%7BRBD26 LJB7HC19](https://user-images.githubusercontent.com/40169984/54572533-f9b14a80-4a22-11e9-808e-328c6a2b6487.png)
检查一下数据的格式是否与readme写的一致，anchor之类的调整没有？

**Comment by ZLXC** [comment]
你好，我碰到和你相同的问题，准确率和召回率都为0，不知道你解决了吗？可否分享一下解决办法，谢谢。

**Comment by madhu-korada** [comment]
Same problem. Please share the solution.

**Comment by dunaizhuan** [comment]
> Same problem. Please share the solution.

Question about recall and acc ,i guess may be the iou must >=0.5 and the model will predict the outcome ,otherwise it will not predict(in paper).you can see it in the program.SO that's may because iou <0.5. By the way the total loss<2,model will save chekpoint in './chekpint'(may be the path?)

**Comment by madhu-korada** [comment]
thank you.
one more question, i am getting an error like this. do you know the reason why
i am using own dataset of 10 classes.


  File "/home/senth/madhu/YOLOv3_TensorFlow-master/utils/data_utils.py", line 140, in process_box
    y_true[feature_map_group][y, x, k, :2] = box_centers[i]

IndexError: index 88 is out of bounds for axis 0 with size 88

Thank you.

**Comment by dunaizhuan** [comment]
> 你好，我碰到和你相同的问题，准确率和召回率都为0，不知道你解决了吗？可否分享一下解决办法，谢谢。

因为iou<0.5 模型当iou大于0.5才会做出预测？你可以在源文件还有论文中看到这一个。 我曾经改了iou<0.3, loss降低了但是他还是没有做出预测（可能iou还是太低了）。我做的一个比赛，是小物体的。因为conf loss 和class loss总是莫名其妙出nan。不做了 继续学习去了。没有解决这一个问题 。顺便提一下 当step%500==0应该是这个并且total loss<2 。他会保存 checkpoint  因该是在‘./checkpoint/’ 这个路径 我不知道他是否会自己创建这个文件夹，你翻下源码吧。记不大清了

**Comment by dunaizhuan** [comment]
> thank you.
> one more question, i am getting an error like this. do you know the reason why
> i am using own dataset of 10 classes.
> 
> File "/home/senth/madhu/YOLOv3_TensorFlow-master/utils/data_utils.py", line 140, in process_box
> y_true[feature_map_group][y, x, k, :2] = box_centers[i]
> 
> IndexError: index 88 is out of bounds for axis 0 with size 88
> 
> Thank you.

sorry, i don't know. perhaps
![$}TVG0L~TUL1CB~GRJM~V%D](https://user-images.githubusercontent.com/40169984/54876608-bf461400-4e4d-11e9-9c67-55e706f95c1f.png)
 you can print(the dimension) in it Like this
 . 88 out of size 88. may be 0 to  87 ,begin with 0?

**Comment by dunaizhuan** [comment]
> thank you.
> one more question, i am getting an error like this. do you know the reason why
> i am using own dataset of 10 classes.
> 
> File "/home/senth/madhu/YOLOv3_TensorFlow-master/utils/data_utils.py", line 140, in process_box
> y_true[feature_map_group][y, x, k, :2] = box_centers[i]
> 
> IndexError: index 88 is out of bounds for axis 0 with size 88
> 
> Thank you.
 solution to ensorflow/core/framework/op_kernel.cc:1261] Invalid argument: TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):

File "H:\py\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in call
ret = func(*args)

File "D:\futurelab\yolo\utils\data_utils.py", line 130, in parse_data
pic_path, boxes, labels = parse_line(line)

File "D:\futurelab\yolo\utils\data_utils.py", line 19, in parse_line
s = line.strip().split(' ')

TypeError: a bytes-like object is required, not 'str'

![Q}T 4NY@T9W0`R)D96YN~ G](https://user-images.githubusercontent.com/40169984/54876986-a4769e00-4e53-11e9-85f8-09135d7a9bd8.png)

**Comment by ZLXC** [comment]
> > 你好，我碰到和你相同的问题，准确率和召回率都为0，不知道你解决了吗？可否分享一下解决办法，谢谢。
> 
> 因为iou<0.5 模型当iou大于0.5才会做出预测？你可以在源文件还有论文中看到这一个。 我曾经改了iou>0.3, loss降低了但是他还是没有做出预测（可能iou还是太低了）。我做的一个比赛，是小物体的。因为conf loss 和class loss总是莫名其妙出nan。不做了 继续学习去了。没有解决这一个问题 。顺便提一下 当step%500==0应该是这个并且total loss<2 。他会保存 checkpoint 因该是在‘./checkpoint/’ 这个路径 我不知道他是否会自己创建这个文件夹，你翻下源码吧。记不大清了

谢谢回复，我用保存好的模型去评估，召回率准确率还是0，iou参数也调过，在检查代码中发现在计算准确率时符合条件的框数目（filter_boxes）一直是0个，所以导致了后面一系列0，不知道是哪儿出了问题，文件等等都已经排查了好多遍了。

**Comment by xiaos16** [comment]
> thank you.
> one more question, i am getting an error like this. do you know the reason why
> i am using own dataset of 10 classes.
> 
> File "/home/senth/madhu/YOLOv3_TensorFlow-master/utils/data_utils.py", line 140, in process_box
> y_true[feature_map_group][y, x, k, :2] = box_centers[i]
> 
> IndexError: index 88 is out of bounds for axis 0 with size 88
> 
> Thank you.

hi, have you solved this problem?

**Comment by madhu-korada** [comment]
Not yet.

**Comment by xiaos16** [comment]
> Not yet.

hi, I found my problem was the box inputs. Maybe the box is outside the image.  You can check it.

**Comment by madhu-korada** [comment]
> > Not yet.
> 
> hi, I found my problem was the box inputs. Maybe the box is outside the image. You can check it.

Yes that was the problem for me too.
Thank you so much.

**Comment by kazim05** [comment]
hi let me tell which annotation have you been used? labelimg or bbox label tool? and what was the format of annotation .xml or .txt?

**Comment by wizyoung** [comment]
Seems that problems get solved.
The previous loss function is buggy and now get fixed.
@kazim05 labelimg. The format is updated in the readme file.

**Comment by wizyoung** [comment]
add a script to generate the needed annotations from VOC xml files. see https://github.com/wizyoung/YOLOv3_TensorFlow/blob/master/misc/parse_voc_xml.py
