### ISSUE TITLE
I don't see the Mutil-scale training

### ISSUE THREAD

**Issue by yanghedada** [wizyoung/YOLOv3_TensorFlow#29]
hi, I don't see the Mutil-scale training.If I go from [416, 416] scale to [512, 512] scale model, will I reset model after saving? 
By loading the trained model of [416, 416], the img_size is set to [512, 512] for retraining. Is it possible to do multi-scale training?
Because I understand that multi-scale training has been set up several scales [320, 416, 512, 640], in the training process each batch randomly selected a size.
Thank you in advance for your assistance。@wizyoung

**Comment by wizyoung** [comment]
Added.
