### ISSUE TITLE
Performance on VOC 2007 test set

### ISSUE THREAD

**Issue by jamiechoi1995** [wizyoung/YOLOv3_TensorFlow#30]
Does anyone try to train on VOC 2007+2012 trainval?

I got only ~0.742 mAP on VOC 2007 test

recall: 0.703, precision: 0.793, total_loss: 0.440, loss_xy: 0.017, loss_wh: 0.007, loss_conf: 0.376, loss_class: 0.040

I apply the 2-stage training:

1. I load the darknet weight first and only train the yolov3_head.
2. When the loss < 2, I lower the learning rate and train the whole model

**Comment by ZLXC** [comment]
Hello, I run the data of voc_2007. Los_xy: 0.7684. Los_wh: 5.0958. Los_conf: 84.3672. Los_class: 9.2975, but recall: 0.0000. Precision: 0.0000. Do you encounter the same situation? Why?

**Comment by wizyoung** [comment]
@jamiechoi1995 If you didn't add other training skills like what I mentioned in the readme, actually 0.74 mAP is the normal performance of YOLOv3 on VOC dataset. Since I've very busy for some personal reasons, I have to pause the update of this repo for weeks. Using this repo, one of my friends has achieved 0.86 mAP on VOC 2007 test set and the core skills are using data augmentation (mixed up is useful), label smoothing, and weight decay. 

For good practice in object detection, I prefer this [paper](https://arxiv.org/pdf/1902.04103.pdf).

Thanks for your participation.

**Comment by jamiechoi1995** [comment]
@ZLXC I haven't met this situation

**Comment by hitzht** [comment]
> @ZLXC I haven't met this situation
i meet a error with this implementation,can you give me some advice?
    s = line.strip().split(' ')
TypeError: a bytes-like object is required, not 'str',
.......
 image, y_true_13, y_true_26, y_true_52 = dataset_iterator.get_next()
 self._traceback = tf_stack.extract_stack()
OutOfRangeError (see above for traceback): End of sequence

**Comment by hitzht** [comment]
> @ZLXC I haven't met this situation

how to calculate map？thanks

**Comment by wizyoung** [comment]
@jamiechoi1995 Code updated. Would you try the new one?

**Comment by jamiechoi1995** [comment]
> 
> 
> @jamiechoi1995 Code updated. Would you try the new one?

Thank you very much, but I'm doing other projects recently :(.

**Comment by wizyoung** [comment]
@jamiechoi1995 That's ok. I'm busy doing other projects too. I spare some time during the may day holidays to finish the todos. Have you added data augmentation or other skills by obtaining 74.2 mAP?

**Comment by jamiechoi1995** [comment]
> 
> 
> Does anyone try to train on VOC 2007+2012 trainval?
> 
> I got only ~0.742 mAP on VOC 2007 test
> 
> recall: 0.703, precision: 0.793, total_loss: 0.440, loss_xy: 0.017, loss_wh: 0.007, loss_conf: 0.376, loss_class: 0.040
> 
> I apply the 2-stage training:
> 
>     1. I load the darknet weight first and only train the yolov3_head.
> 
>     2. When the loss < 2, I lower the learning rate and train the whole model

I just following these settings @wizyoung

**Comment by wizyoung** [comment]
@jamiechoi1995 Did you add data augmentation yourself?

**Comment by jamiechoi1995** [comment]
@wizyoung no

**Comment by wizyoung** [comment]
@jamiechoi1995 Wow, that's amazing. As [Gloun-cv](https://arxiv.org/pdf/1902.04103.pdf) only achieved ~0.64 mAP without data augmentation. I trained the model without data augmentation a week ago and only got about 0.70 mAP. How's your learning rate setting in the two stage schedule? And I guess the loss in `loss < 2` you mentioned is the training loss?

**Comment by jamiechoi1995** [comment]
@wizyoung I use your eval.py to calculate

**Comment by wizyoung** [comment]
@jamiechoi1995 But I didn't include the mAP calculation in the old version.

**Comment by jamiechoi1995** [comment]
@wizyoung wow, maybe I thought precision = mAP? I was not familiar with precision and mAP at that time. Just ignore my result :(

**Comment by wizyoung** [comment]
@jamiechoi1995 It doesn't matter. Actually your loss is pretty low which is better than mine. And your precision and recall is good. Anyway, thanks for your participation.

**Comment by jamiechoi1995** [comment]
@wizyoung I think the low loss is due to my small learning rate.
Thank you for writing these codes, your implementation is easy to use when compared with other codes.
