### ISSUE TITLE
Problem of 'y_true' in data_utils.py

### ISSUE THREAD

**Issue by weiluo1992** [wizyoung/YOLOv3_TensorFlow#31]
When I train  my own data by your model , I meet this problem as flow,  and I  wolud give your my data , thank you！！！

[train.txt](https://github.com/wizyoung/YOLOv3_TensorFlow/files/2992537/train.txt)

  File "D:\Project_Data\YOLOv3_TensorFlow\utils\data_utils.py", line 122, in process_box
    y_true[feature_map_group][y, x, k, 5+c] = 1.

IndexError: index 10 is out of bounds for axis 3 with size 10

**Comment by YUHAO19910716** [comment]
你看看,你的dataes.names那个文件.在最后一行多加几个空行,看看能不能解决
