### ISSUE TITLE
training probrem

### ISSUE THREAD

**Issue by CherishineNi** [wizyoung/YOLOv3_TensorFlow#32]
How to solve this problem, great god, help me!
![6IL{)0B4 WZ4L84BL`9G 4X](https://user-images.githubusercontent.com/44666138/54804169-84a57580-4cad-11e9-8a39-81e64f6e7722.png)

**Comment by madhu-korada** [comment]
same problem.

**Comment by wizyoung** [comment]
duplicate of https://github.com/wizyoung/YOLOv3_TensorFlow/issues/33
