### ISSUE TITLE
loss nan

### ISSUE THREAD

**Issue by YUHAO19910716** [wizyoung/YOLOv3_TensorFlow#34]
笔者你好,我用您的模型训练4类,人 ,车,交通灯,自行车.
我重新实现了您的代码.网络也能跑起来! 在此十分感谢

前期跑很正常.loss都下降.但是不知何时我的loss就变NaN了.请问这是什么问题呢?

我没有做自己的数据增强.
谢谢啦.

**Comment by xiaos16** [comment]
> 笔者你好,我用您的模型训练4类,人 ,车,交通灯,自行车.
> 我重新实现了您的代码.网络也能跑起来! 在此十分感谢
> 
> 前期跑很正常.loss都下降.但是不知何时我的loss就变NaN了.请问这是什么问题呢?
> 
> 我没有做自己的数据增强.
> 谢谢啦.

try a smaller lr.

**Comment by YUHAO19910716** [comment]
@xiaos16  谢谢,我正在用lr=0.0001跑比作者的小了10倍,我用作者的lr=0.001跑会出现该问题.现在lossall在10左右浮动.也不知道最终的结果能有多少 
![99999](https://user-images.githubusercontent.com/40976524/55303034-88d44e80-5476-11e9-8c26-321523809cee.png)

**Comment by xiaos16** [comment]
> @xiaos16 谢谢,我正在用lr=0.0001跑比作者的小了10倍,我用作者的lr=0.001跑会出现该问题.现在lossall在10左右浮动.也不知道最终的结果能有多少
> ![99999](https://user-images.githubusercontent.com/40976524/55303034-88d44e80-5476-11e9-8c26-321523809cee.png)

Check the recall and precision,  you can stop training when it satisfied.
If you want decrease the loss,  try lr = lr/10  when the loss is stable, it may help.

**Comment by YUHAO19910716** [comment]
@xiaos16 谢谢您的建议. 我用coco2017_train数据集,用其中一部分当验证,但是这个部分没有被训练.
![777](https://user-images.githubusercontent.com/40976524/55311049-9ac4ea00-5494-11e9-9f72-a8070b5d270c.png).

**Comment by xiaos16** [comment]
> @xiaos16 谢谢您的建议. 我用coco2017_train数据集,用其中一部分当验证,但是这个部分没有被训练.
> ![777](https://user-images.githubusercontent.com/40976524/55311049-9ac4ea00-5494-11e9-9f72-a8070b5d270c.png).

I say, check the recall and precision of the validation dataset...

**Comment by YUHAO19910716** [comment]
@xiaos16 明白,我这就看看,顺便请问下您.你在验证数据集的召回率,和精度达到多少了.

**Comment by wonderfulboy** [comment]
请问你用的learning rate 一直是0.0001， 不下降吗？

**Comment by wonderfulboy** [comment]
> 笔者你好,我用您的模型训练4类,人 ,车,交通灯,自行车.
> 我重新实现了您的代码.网络也能跑起来! 在此十分感谢
> 
> 前期跑很正常.loss都下降.但是不知何时我的loss就变NaN了.请问这是什么问题呢?
> 
> 我没有做自己的数据增强.
> 谢谢啦.

请问，你用的learning rate 一直是 0.0001，不随着训练次数减小吗？

**Comment by YUHAO19910716** [comment]
@wonderfulboy 我用的是adam优化器,这个优化器会自动降低学习率.我不能用0.0001用了网络会nan,我用0.00001这样网络可以训练.

**Comment by wonderfulboy** [comment]
@YUHAO19910716 用了adam优化器的话，--lr_type就选择“fixed”吗？

**Comment by YUHAO19910716** [comment]
@wonderfulboy  这个你点自己取查了.

**Comment by wizyoung** [comment]
fixed with new warm up codes.
