### ISSUE TITLE
leaky_relu or relu

### ISSUE THREAD

**Issue by wonderfulboy** [wizyoung/YOLOv3_TensorFlow#37]
作者你好，看原版yolov3的cfg文件，激活层用的是leaky，而这里用的是默认的relu，这个没有影响吗？

**Comment by wizyoung** [comment]
Watch the source codes carefully.

**Comment by wonderfulboy** [comment]
> Watch the source codes carefully.

不好意思，没看仔细。再请教一下，如果 优化器选择了“adam”， 那 lr_type 应该选择 “fixed”吗？

**Comment by wizyoung** [comment]
Not necessarily, you can also choose other types.

**Comment by wonderfulboy** [comment]
> Not necessarily, you can also choose other types.

好的，谢谢！

**Comment by wonderfulboy** [comment]
![image](https://user-images.githubusercontent.com/19703978/55711896-4388c180-5a20-11e9-85f2-0cf12297504a.png)

训练时，loss_conf 占了 total_loss 中 80% 以上的比例，这个正常吗？
