### ISSUE TITLE
自己的训练数据集问题

### ISSUE THREAD

**Issue by answer123answe** [wizyoung/YOLOv3_TensorFlow#38]
笔者，您好！希望您在百忙之中可以看到我的请教，希望您可以赐教。万分感谢！
请问您写的这个yolov3版本的新数据集的制作是如何制作的呢？是不是和原版yolov3的不太一样呢？
请问在您示例当中写的xxx/xxx/1.jpg 0 453 369 473 391 1 588 245 608 268中数字的顺序是：类别，方框左上角x坐标，方框左上角y坐标，方框右下角x坐标，方框右下角y坐标的书序吗？
关于自己数据集的制作请问您有相关文章链接吗？大致步骤是怎样的呢？
谢谢

**Comment by olwolf** [comment]
你好，请问你解决这个问题了吗？我也遇到了这个难题

**Comment by Corvo69** [comment]
对于labelImg标的Annotation文件，可以参考下面的做法，可以做成作者那种数据集格式。

`def create_txt(a_path, p_path, name):
    """
    把一个类的标注文件按[pic_path, box1. box2..]格式导出txt文件
    :param a_path: 标注文件的路径
    :param p_path: 图片文件的路径
    :param name: 类别名称
    """
    import xml.etree.ElementTree as ET
    save_path = 'H:/train_txt/'
    xml_list = []
    temp_list = []
    pic_list = []
    # 文件名相同 后缀不同
    for root1, _, files1 in os.walk(p_path):
        for file1 in files1:
            pic_name = file1.split('.')[0]
            pic_path = join(root1, file1)
            pic_list.append([pic_name, pic_path])
    for root2, _, files2 in os.walk(a_path):
        for file2 in files2:
            a_path = None
            a_name = file2.split('.')[0]
            for index, _file in enumerate(pic_list):
                if _file[0] == a_name:  # 标注文件存在必存在图片 不需要无标注文件的图片
                    a_path = _file[1]  # 图片绝对路径
                    pic_list.pop(index)
                    break
            xml_file = join(root2, file2)
            if a_path is None:
                raise FileNotFoundError('{}图像文件不存在'.format(a_name))

            tree = ET.parse(xml_file)  # 读取文件
            root = tree.getroot()
            for member in root.findall('object'):  # 返回所有匹配的子元素列表
                raw_label = member.find('name').text
                if raw_label not in labels:  # 获取特定类的框信息
                    continue
                label = my_data_map(raw_label)  # class -> number
                xmin = int(member[4][0].text)
                ymin = int(member[4][1].text)
                xmax = int(member[4][2].text)
                ymax = int(member[4][3].text)
                temp_list += [label, xmin, ymin, xmax, ymax]
            output = [a_path] + temp_list
            temp_list.clear()
            xml_list.append(output)

    print('开始写入文件{}..'.format(name))
    with open(save_path + '{}'.format(name), 'w') as f:
        for row in xml_list:
            s = ''
            for item in row:
                s += str(item)
                s += ' '
            s.rstrip()
            s += '\n'
            f.write(s)
    print('{}文件写入完毕'.format(name))`

**Comment by gzz1529657064** [comment]
> 笔者，您好！希望您在百忙之中可以看到我的请教，希望您可以赐教。万分感谢！
> 请问您写的这个yolov3版本的新数据集的制作是如何制作的呢？是不是和原版yolov3的不太一样呢？
> 请问在您示例当中写的xxx/xxx/1.jpg 0 453 369 473 391 1 588 245 608 268中数字的顺序是：类别，方框左上角x坐标，方框左上角y坐标，方框右下角x坐标，方框右下角y坐标的书序吗？
> 关于自己数据集的制作请问您有相关文章链接吗？大致步骤是怎样的呢？
> 谢谢

你没仔细看吧。应该是 序号 xxx/xxx/1.jpg 0 453 369 473 391

**Comment by eain3314** [comment]
> > 笔者，您好！希望您在百忙之中可以看到我的请教，希望您可以赐教。万分感谢！
> > 请问您写的这个yolov3版本的新数据集的制作是如何制作的呢？是不是和原版yolov3的不太一样呢？请问
> > 在您示例当中写的xxx / xxx / 1.jpg 0 453 369 473 391 1 588 245 608 268中数字的顺序是：类别，方框左上角x坐标，方框左上角Ÿ坐标，方框右下角X坐标，方框右下角ÿ坐标的书序吗？
> > 关于自己数据集的制作请问您有相关文章链接吗？大致步骤是怎样的呢？
> > 谢谢
> 
> 你没仔细看吧。应该是序号xxx / xxx / 1.jpg 0 453 369 473 391

请问 你有标注的代码吗？或者怎么标注的，麻烦告诉我一下谢谢 微信：lyb864770486

**Comment by hhhsahb** [comment]
我也不懂,老哥解决了吗

**Comment by wizyoung** [comment]
无论用什么标注软件都可以，最后转换成这个格式就行，不复杂。标注格式不重要，数据对了就行。
