### ISSUE TITLE
Assign requires shapes of both tensors to match error

### ISSUE THREAD

**Issue by stq054188** [wizyoung/YOLOv3_TensorFlow#42]
I have trained a model successfully, but when i use test_single_image.py to test it showed error as follow, I can't find the reason, can anyone help me? thanks.

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1,1,1024,21] rhs shape= [1,1,1024,255]
	 [[Node: save/Assign_350 = Assign[T=DT_FLOAT, _class=["loc:@yolov3/yolov3_head/Conv_6/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](yolov3/yolov3_head/Conv_6/weights, save/RestoreV2/_701)]]
	 [[Node: save/RestoreV2/_372 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_378_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:186)]]

**Comment by stq054188** [comment]
@wizyoung Can you give me some advice, thanks.

**Comment by chen3718** [comment]
@stq054188 did you solve it?

**Comment by ongspxm** [comment]
i saw this qns too, i am facing the same issue as well, any fixes? #133

**Comment by dlutzhouyue** [comment]
same issue
