### ISSUE TITLE
Question about 5dims tensor

### ISSUE THREAD

**Issue by philipwan** [wizyoung/YOLOv3_TensorFlow#43]
楼主好，请问一下为什么yolov3要用reshape将四维tensor转换成5维，是因为这样更适配于GPU还是其他的原因？

**Comment by philipwan** [comment]
Very curious about this question~

**Comment by wizyoung** [comment]
请详细描述你的问题

**Comment by philipwan** [comment]
> 请详细描述你的问题

对于yolov3中5维tensor，在我现在使用的板卡上不支持，所以我现在的想法是将5维tensor全部都reshape成4维，但是又不知道会不会对模型有影响，所以想知道yolov3中的5维tensor作用是什么，可不可以直接转换。

**Comment by wizyoung** [comment]
5 维的意思是 [batch_size, feat_h, feat_h, 3, 6 + num_class]. 3 是因为有 3 个 level. 其实要做成 4 维也是可以的，把最后两个合并一下。这样的话整个模型部分的回归，损失计算部分都要相应改动一下。找到原来 5 维对应的索引位置。

**Comment by philipwan** [comment]
> 5 维的意思是 [batch_size, feat_h, feat_h, 3, 6 + num_class]. 3 是因为有 3 个 level. 其实要做成 4 维也是可以的，把最后两个合并一下。这样的话整个模型部分的回归，损失计算部分都要相应改动一下。找到原来 5 维对应的索引位置。

目前我只想使用pb做推理部分，应该还涉及不到损失计算之类的，多谢大佬的讲解，我这部分还不是很了解，需要再研究一下。另外还想问int64这种数据类型在训练以及推理中有何作用呢？按我的理解int32就够用了。。。

**Comment by wizyoung** [comment]
嗯嗯，多看下代码吧，其实不是很复杂。
是的，使用 int32 就够了，但是我为了要加快训练，使用 tf.data 来构建高效的输入 pipeline，这样基本上训练时 GPU 利用率可以基本到 100%，训练时间开销相比 placeholder 可以减少多达 30% 的时间（在我的测试下）。然而 tf.data 不知道 tf 怎么想的，只支持 int64，没有办法。单纯推理的话，可以用 placeholder，使用 int32 就行了

**Comment by philipwan** [comment]
> 嗯嗯，多看下代码吧，其实不是很复杂。
> 是的，使用 int32 就够了，但是我为了要加快训练，使用 tf.data 来构建高效的输入 pipeline，这样基本上训练时 GPU 利用率可以基本到 100%，训练时间开销相比 placeholder 可以减少多达 30% 的时间（在我的测试下）。然而 tf.data 不知道 tf 怎么想的，只支持 int64，没有办法。单纯推理的话，可以用 placeholder，使用 int32 就行了

非常感谢了，我争取这两天搞懂这些，感觉yolov3还是很有必要弄明白的
