### ISSUE TITLE
training error, just cant fix it

### ISSUE THREAD

**Issue by wobuxie1997** [wizyoung/YOLOv3_TensorFlow#44]
i got an error when i try to train my own dataset.

![捕获](https://user-images.githubusercontent.com/34472834/57238592-56f96d80-705c-11e9-8164-ce1cc657b674.PNG)

is that because i work it on windows?
i found someone saying it working correctly on Linux when i google this error.
could you please help me?

**Comment by wizyoung** [comment]
You can try changing the first np.asarray function of this [line](https://github.com/wizyoung/YOLOv3_TensorFlow/blob/master/utils/data_utils.py#L213) to `np.asarray(img_idx_batch, np.int64)`.

**Comment by wobuxie1997** [comment]
> You can try changing the first np.asarray function of this [line](https://github.com/wizyoung/YOLOv3_TensorFlow/blob/master/utils/data_utils.py#L213) to `np.asarray(img_idx_batch, np.int64)`.

非常感谢您的回答，解决我的问题。但当程序训练时，会训练一小会儿，然后提示
![TIM截图20190507013238](https://user-images.githubusercontent.com/34472834/57243175-038d1c80-7068-11e9-945b-1634284e781c.png)
我觉得可能是下面这个语句有问题，我将其修改为np.full(shape=(boxes.shape[0], 4)
![捕获](https://user-images.githubusercontent.com/34472834/57243047-ad1fde00-7067-11e9-8c62-dc60e2fee795.PNG)
训练时间变得稍微久了一点，但是仍会报错，不知道是哪出了问题，希望您空闲时能帮我参考一下。

**Comment by wobuxie1997** [comment]
我对程序进行了单步调试，发现有时候img=cv2.imread(pic_path)有时候img的值会是0，不知道是不是在这个地方出了错误

**Comment by wobuxie1997** [comment]
![TIM截图20190507234237](https://user-images.githubusercontent.com/34472834/57313265-d2712280-7121-11e9-9f3e-90d4d07de4d0.png)
我将bitch_size设置为1，可以比较清晰的看出错误的原因，请问这样的错误是因为我数据集的原因吗？从网上查阅资料说该问题是将不同维度的数组合为一个会出现这样的错误，但是我train.txt是严格要求您的资料里面的要求的，为何会出现这样的报错呢？

**Comment by wizyoung** [comment]
txt文件最后一行加一个空行试试？

**Comment by wobuxie1997** [comment]
我好像找到问题了，问题在于train.txt里面的一些图片可能没有检测对象，即boxes，我手动删除这些没有boxes只有img_path的空行后，就可以正常训练了，被这个困扰两天。。。非常感谢您的代码，对我的毕业设计有很大的帮助。

**Comment by wizyoung** [comment]
不用谢，yolo v3 的训练似乎有技巧，值得探索下，好几个网友都和我反馈训练的挺好的，我自己都没他们训的好hhh
