### ISSUE TITLE
Run test_single_image.py only get FPS 10

### ISSUE THREAD

**Issue by shen338** [wizyoung/YOLOv3_TensorFlow#45]
Hi wizyoung: 

Thank you for providing this awesome repo! 

Based on my test, it takes around 100s to run `boxes_, scores_, labels_ = sess.run([boxes, scores, labels], feed_dict={input_data: img})` 1000 times with a 416x416 image. This speed is nearly 5 times slower than 23ms you claimed. I didn't change anything on your  test_single_image.py file. 

Could you help me a little bit with this? 

Thank you!

**Comment by shen338** [comment]
By the way, I am using a 32G V100 GPU, with CUDA 9.0 and CuDNN 7.

**Comment by shen338** [comment]
I use your CPU NMS instead, the speed is boosted up to 80 FPS. 

There should be something wrong with TF gpu nms. Thank you for this amazing work! @wizyoung

**Comment by wizyoung** [comment]
Thanks for your report. I take a glance and the code is indeed not well optimized. You can refer to [train.py](https://github.com/wizyoung/YOLOv3_TensorFlow/blob/master/train.py) that places model and gpu nms op before the session. I will update the code later today when I have time.

**Comment by shen338** [comment]
> > I use your CPU NMS instead, the speed is boosted up to 80 FPS.
> > There should be something wrong with TF gpu nms. Thank you for this amazing work! @wizyoung
> 
> Hello, I also tried to use cpu_nms to solve the speed problem, but there was an error.The error is as follows:AttributeError: 'Tensor' object has no attribute 'reshape'.How did you solve it?

I didn't have this problem. 

Could you please specify your error or report the full error message and location? I cannot spot this error in the code.

**Comment by wizyoung** [comment]
@shen338 On my machine, the speed is fast except for the first image. The first image will take a lot of time. I just tested 10 images in a for loop, the time cost is:
```
2623.04902077
28.8169384003
29.2549133301
26.9999504089
28.8610458374
28.0549526215
28.1419754028
28.5141468048
28.6440849304
29.492855072
```

**Comment by james5551** [comment]
> > > I use your CPU NMS instead, the speed is boosted up to 80 FPS.
> > > There should be something wrong with TF gpu nms. Thank you for this amazing work! @wizyoung
> > 
> > 
> > Hello, I also tried to use cpu_nms to solve the speed problem, but there was an error.The error is as follows:AttributeError: 'Tensor' object has no attribute 'reshape'.How did you solve it?
> 
> I didn't have this problem.
> 
> Could you please specify your error or report the full error message and location? I cannot spot this error in the code.
Traceback (most recent call last):
  File "test_single_image.py", line 60, in <module>
    boxes, scores, labels = cpu_nms(pred_boxes, pred_scores, args.num_class, max_boxes=100, score_thresh=0.4, iou_thresh=
0.5)
  File "D:\YOLOv3_TensorFlow-master\YOLOv3_TensorFlow-master\utils\nms_utils.py", line 133, in cpu_nms
    boxes = boxes.reshape(-1, 4)
AttributeError: 'Tensor' object has no attribute 'reshape'

**Comment by james5551** [comment]
> > > > I use your CPU NMS instead, the speed is boosted up to 80 FPS.
> > > > There should be something wrong with TF gpu nms. Thank you for this amazing work! @wizyoung
> > > 
> > > 
> > > Hello, I also tried to use cpu_nms to solve the speed problem, but there was an error.The error is as follows:AttributeError: 'Tensor' object has no attribute 'reshape'.How did you solve it?
> > 
> > 
> > I didn't have this problem.
> > Could you please specify your error or report the full error message and location? I cannot spot this error in the code.
> > Traceback (most recent call last):
> > File "test_single_image.py", line 60, in 
> > boxes, scores, labels = cpu_nms(pred_boxes, pred_scores, args.num_class, max_boxes=100, score_thresh=0.4, iou_thresh=
> > 0.5)
> > File "D:\YOLOv3_TensorFlow-master\YOLOv3_TensorFlow-master\utils\nms_utils.py", line 133, in cpu_nms
> > boxes = boxes.reshape(-1, 4)
> > AttributeError: 'Tensor' object has no attribute 'reshape'

Mistakes don't think tensor reshape properties
