### ISSUE TITLE
Error regarding 'exception'

### ISSUE THREAD

**Issue by khbadii** [wizyoung/YOLOv3_TensorFlow#48]
Hello

I tried to train my data, but I received the below error:
[[{{node PyFunc}}]]
[[{{node ITeratorGetNext}}]]

'During handling of the above exception, another exception occurred:'

[[{{node PyFunc}}]]
[[node ITeratorGetNext (defined at train.py: 60) ]]

and line 60 is:
image_ids, image, y_true_13, y_true_26, y_true_52 = iterator.get_next()

My system has no GPU and I am running the program on CPU. How can I solve it?

Regards

**Comment by xliu79** [comment]
same problem.I already trained my custom data with old version.But cannot make it with new version

**Comment by wizyoung** [comment]
Please report your detailed hardware and software environments(like tf version, python version). I'll look into this issue at this weekend.

**Comment by khbadii** [comment]
Thanks a lot.
Please find below the hardware specifications:
Processor: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Installed RAM: 4.00 GB
System type: 64-bit operating system, x64-based processor

, environments:
Python: version 3.7.2
TF: version 1.13.1 (some parts 2.0)
anaconda command line: version 1.7.2

, and the error on the screen:
Traceback (most recent call last):
 File "C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
          return fn(*args)
 File C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
         options, feed_dict, fetch_list, target_list, run_metadata)
 File C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow\python\client\session.py", line 1334, in _call_tf_sessionrun
         run_metadata)
tensorflow.python, framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_0 is int32, but experts int64
                               [[{{node PyFunc}}]]
                               [[{{node ITeratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "train.py" line 140, in <module>
   feed_dict={is_training: True})
 File "C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow\python\client\session.py", line 929, in run
          run_metadata_ptr)
 File C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
         feed_dict_tensor, options, run_metadata)
 File C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
         run_metadata)
 File C:\ProgramData\Anaconda3\Lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
         raise type(e)(node_def, op, message)
tensorflow.python, framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_0 is int32, but experts int64
                                  [[{{node PyFunc}}]]
                                  [[node ITeratorGetNext (defined at train.py: 60) ]]

Note: the number of lines may be different from the original train.py file. I added some 'print()' to follow the procedure.  They have no effect on the process.
[progress.log](https://github.com/wizyoung/YOLOv3_TensorFlow/files/3160454/progress.log)]

**Comment by wizyoung** [comment]
From the log you provided, I guess it's system platform related. For a quick fix, you may try changing the first np.asarray function of this [line](https://github.com/wizyoung/YOLOv3_TensorFlow/blob/master/utils/data_utils.py#L213) to `np.asarray(img_idx_batch, np.int64)`.

**Comment by eain3314** [comment]
Gradient exploded! Please train again and you may need modify some parameters.
how to solve it？

**Comment by khbadii** [comment]
Hello

Thanks. That problem has been solved and it built a model with the following name in checkpoint sub-directory:
"best_model_Epoch_9_step_190.0_mAP_0.0007_loss_141.8792_lr_0.00096"
, but the training program has been stopped with the following message (line number may be changed due to adding some print command):
Traceback (most recent call last):
   File "train.py",line 170, in <module>
     if loss_total.last_avg <= 2.:
AttributeError: 'AverageMeter' object has no attribute 'last_avg'
Is it serious? How can I solve it? Please find the attached file as the 'log' file:
[progress.log](https://github.com/wizyoung/YOLOv3_TensorFlow/files/3168365/progress.log)
Thanks again.

**Comment by qfzack** [comment]
> Hello
> 
> Thanks. That problem has been solved and it built a model with the following name in checkpoint sub-directory:
> "best_model_Epoch_9_step_190.0_mAP_0.0007_loss_141.8792_lr_0.00096"
> , but the training program has been stopped with the following message (line number may be changed due to adding some print command):
> Traceback (most recent call last):
> File "train.py",line 170, in 
> if loss_total.last_avg <= 2.:
> AttributeError: 'AverageMeter' object has no attribute 'last_avg'
> Is it serious? How can I solve it? Please find the attached file as the 'log' file:
> [progress.log](https://github.com/wizyoung/YOLOv3_TensorFlow/files/3168365/progress.log)
> Thanks again.

I had the same problem, 'AverageMeter' object has no attribute 'last_avg' ,how did you solve it?

**Comment by henbucuoshanghai** [comment]
AttributeError: 'AverageMeter' object has no attribute 'last_avg'
why？？？？？？？？？？？？？？？？？？？？？
