### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by abeyang00** [wizyoung/YOLOv3_TensorFlow#5]
I get a training error as shown below
![screenshot from 2019-01-27 11-47-15](https://user-images.githubusercontent.com/36392866/51795590-5c5b4680-2229-11e9-8b5c-abcfd2d1c2c6.png)

I have no negative samples in my train.txt and i left a blank line at the end of both train.txt and val.txt
[test.txt](https://github.com/wizyoung/YOLOv3_TensorFlow/files/2799706/test.txt)
[train.txt](https://github.com/wizyoung/YOLOv3_TensorFlow/files/2799705/train.txt)

What can be the problem for this error?

**Comment by wizyoung** [comment]
can you attach the dataset link? The information you offer is not enough. If you are unwilling to post it here, you can contact with me through email.

**Comment by abeyang00** [comment]
@wizyoung What do you mean by dataset link? I'm using my own dataset (I acquired them myself) and its saved on my computer. I can send you them but it's very large

**Comment by wizyoung** [comment]
I have no idea why the error occurs. So I need the data to analyze myself. Can you figure out which image in your dataset triggers the error? For example, in the image above, images after 60 (global step) * batch_size trigger the error, you can find them out and send to me for analysis.

**Comment by abeyang00** [comment]
@wizyoung Actually, i just figured it out. The problem was because my label didn't start from 0.

Also, is there a way to visualize training images on tensorboard?

**Comment by abeyang00** [comment]
I have changed batch_size to 1 and got 
Epoch: 0, global_step: 97, total_loss: 93.189, loss_xy: 0.409, loss_wh: 1.121, loss_conf: 86.683, loss_class: 4.976
2019-01-27 12:18:04.363404: W tensorflow/core/framework/op_kernel.cc:1202] OP_REQUIRES failed at iterator_ops.cc:870 : Unknown: exceptions.IndexError: index 26 is out of bounds for axis 1 with size 26
         [[Node: PyFunc = PyFunc[Tin=[DT_STRING, DT_INT32, DT_INT32, DT_FLOAT, DT_STRING], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](arg0, PyFunc/input_1, PyFunc/input_2, PyFunc/input_3, PyFunc/input_4)]]
Traceback (most recent call last):

97th image in train.txt is 
![screenshot from 2019-01-27 12-19-44](https://user-images.githubusercontent.com/36392866/51795894-d7bef700-222d-11e9-9f77-2ab4b0666113.png)

![1159](https://user-images.githubusercontent.com/36392866/51795896-e1485f00-222d-11e9-91d3-b5dcdc9efdbe.jpg)

**Comment by abeyang00** [comment]
Yeah i'm pretty sure i'm offering the correct image and label. Labels are supposed to start from 0 right? and if it stops at global stop 97, does that mean 97th image is causing the error or 98th?

**Comment by wizyoung** [comment]
The 97th epoch gives the loss, so it should be the 98th image causing the error

**Comment by abeyang00** [comment]
Ok. I'm debugging with 100 images and it still occurs.
I sent you an email with my train.txt anchor and 100 images that i'm using

**Comment by madhu-korada** [comment]
Can you elaborate how your error has been resolved.
