### ISSUE TITLE
A probrem of gpu_nms() got an unexpected keyword argument 'iou_thresh'

### ISSUE THREAD

**Issue by MrWXfaster** [wizyoung/YOLOv3_TensorFlow#52]
iou_thresh change nms_thresh

**Comment by zhanglsky** [comment]
Did you fixed this problem? I got the same error

**Comment by CNUyue** [comment]
I got the same error!

**Comment by MrWXfaster** [comment]
把出现文件iou thresh改为nms thresh
就可以了。

**Comment by zhanglsky** [comment]
> 把出现文件iou thresh改为nms thresh
> 就可以了。

谢谢，可以了

**Comment by Ragas99205** [comment]
just change the word iou_thresh to nms_thresh.

**Comment by wizyoung** [comment]
thanks. fixed.
