### ISSUE TITLE
关于K-means的问题

### ISSUE THREAD

**Issue by StrongBirds** [wizyoung/YOLOv3_TensorFlow#54]
首先感谢你的代码，
1，我在运行get_kmeans.py时运行出来anchors的[w， h]是相对于416*416图片的尺寸吗？好像你的anchors是相对于原图片的尺寸得到的，我没有看到对anchors的resize，而且在训练的时候好像也没有对anchors进行resize，
2， 直接把原图片resize到416×416是否合理，这样会不会破坏了原目标的尺寸比例关系，
若有理解错的地方请指正，谢谢了

**Comment by wizyoung** [comment]
**输入**到模型的 anchor 是针对 resize 后 (比如 416\*416) 大小而言的，如果要直接把原图 resize 到一个尺寸，要么先把坐标 resize 好，再计算 anchor，或者先计算好，再除以 resize 比例。你提到的，直接 resize 是否合理，会不会破坏比例关系，得看你的数据集情况了，比如同一个数据集，有人直接暴力 resize，有人通过 padding 0 来保持比例，效果肯定是有差异的，哪个更好不好说，得实验。鉴于 yolov3 输入可以是任意尺寸，你甚至可以输入 416 \* 640 这样的方形尺寸来贴近你原始的图片比例。其实 anchor 作为一种参考，只要能大致覆盖到各尺度尺寸就行，差一点，最后的实验结果影响不是很大。

为什么我的 kmeans 脚本直接针对原图做呢？考虑 5120 \* 5120 高分辨率的图像，最小的目标尺寸只有 10\*10左右，显然 resize 到 512\*512 是不合理的。我们针对原图求 kmeans，获得原图缩放比下的 anchor，然后训练时，每次从一张高清图中多 crop 出 n 个 512\*512 区域组成训练集。最后测试时，还是利用这些 anchor，但是输入一整 5120\*5120 的图进行测试就可以完美测试出来。

所以不同的人，不同的数据集有不同的需要，我提供的版本仅是一种处于我个人需要的参考，并不是说 kmeans 算完直接扔进模型不管了。其他的需求我希望参考者根据自己需求来修改代码，而不是一味伸手要。

希望这份代码能帮助更多人理解 yolov3 这个非常优秀的模型。里面还有一些小问题，最近太忙实在没时间维护，有时间甚至还想重构一下...

**Comment by StrongBirds** [comment]
> **输入**到模型的 anchor 是针对 resize 后 (比如 416*416) 大小而言的，如果要直接把原图 resize 到一个尺寸，要么先把坐标 resize 好，再计算 anchor，或者先计算好，再除以 resize 比例。你提到的，直接 resize 是否合理，会不会破坏比例关系，得看你的数据集情况了，比如同一个数据集，有人直接暴力 resize，有人通过 padding 0 来保持比例，效果肯定是有差异的，哪个更好不好说，得实验。鉴于 yolov3 输入可以是任意尺寸，你甚至可以输入 416 * 640 这样的方形尺寸来贴近你原始的图片比例。其实 anchor 作为一种参考，只要能大致覆盖到各尺度尺寸就行，差一点，最后的实验结果影响不是很大。
> 
> 为什么我的 kmeans 脚本直接针对原图做呢？考虑 5120 * 5120 高分辨率的图像，最小的目标尺寸只有 10*10左右，显然 resize 到 512*512 是不合理的。我们针对原图求 kmeans，获得原图缩放比下的 anchor，然后训练时，每次从一张高清图中多 crop 出 n 个 512*512 区域组成训练集。最后测试时，还是利用这些 anchor，但是输入一整 5120*5120 的图进行测试就可以完美测试出来。
> 
> 所以不同的人，不同的数据集有不同的需要，我提供的版本仅是一种处于我个人需要的参考，并不是说 kmeans 算完直接扔进模型不管了。其他的需求我希望参考者根据自己需求来修改代码，而不是一味伸手要。
> 
> 希望这份代码能帮助更多人理解 yolov3 这个非常优秀的模型。里面还有一些小问题，最近太忙实在没时间维护，有时间甚至还想重构一下...
感谢你的回复。

**Comment by StrongBirds** [comment]
感谢你的回复。
