### ISSUE TITLE
请问作者的精度能达到darknet吗？

### ISSUE THREAD

**Issue by nobody-cheng** [wizyoung/YOLOv3_TensorFlow#55]
请问作者的精度能达到darknet吗？ 使用下面两个图都是使用darknet训练模型， score_thresh=0.1, iou_thresh=0.45 同样阈值， 但是在提供的代码直接跑test_single_image.py文件（第一张图），结果相差有点出入，请问能提供建议吗？（第二张是使用官方提供预测代码结果）
![detection_result](https://user-images.githubusercontent.com/34908468/57612236-0b3c4c00-75a7-11e9-8cca-2eea1cafad81.jpg)

![00_res](https://user-images.githubusercontent.com/34908468/57611933-789bad00-75a6-11e9-9ff0-2f41cb9aec89.jpg)

**Comment by eain3314** [comment]
你好，能加一下好友吗，我也是做人头的微信lyb864770486

**Comment by wizyoung** [comment]
@nobody-cheng test_single_image 默认只显示 30 个 box，可以增大一下. 权重我是直接转换的 darknet 的 weights，理论上是没有误差的，因此你这个问题我也很好奇. 另外你的 head 分类是怎么来的，输入图像的分辨率有调整吗，anchor 有没有变化

**Comment by eain3314** [comment]
我的那个问题要怎么解决呢…

**Comment by nobody-cheng** [comment]
> @nobody-cheng test_single_image 默认只显示 30 个 box，可以增大一下. 权重我是直接转换的 darknet 的 weights，理论上是没有误差的，因此你这个问题我也很好奇. 另外你的 head 分类是怎么来的，输入图像的分辨率有调整吗，anchor 有没有变化
图像是3072*1364，进网络同样resize成[416， 416]，anchors默认，调整maxbox后的效果还是有点点出入，下面是调整后的图
![detection_result](https://user-images.githubusercontent.com/34908468/57745482-ec9d9880-76ff-11e9-9ff4-3eab5ab7864a.jpg)

**Comment by wizyoung** [comment]
@nobody-cheng 原版的 darknet 你是直接 resize 还是调用作者提供的 letter box resize

**Comment by bujianyiwang** [comment]
请问有从rtsp流每隔n帧跑yolov3检测实时人数的脚本吗？

**Comment by eain3314** [comment]
这样的吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午2:12
收件人:&nbsp;"wizyoung/YOLOv3_TensorFlow"<YOLOv3_TensorFlow@noreply.github.com&gt;;
抄送:&nbsp;"864770486"<864770486@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wizyoung/YOLOv3_TensorFlow] 请问作者的精度能达到darknet吗？ (#55)




请问有从rtsp流每隔n帧跑yolov3检测实时人数的脚本吗？

**Comment by bujianyiwang** [comment]
@eain3314 你是说写过测试rtsp流行人检测的代码？我之前用过以下来跳帧做行人检测，可是这个repo改出来小问题太多，没法用
 # count arguments
    parser.add_argument('--interval', type=int, default=5, help='loops interval for yolo detect')
    parser.add_argument("--frame_hop", type=int, default=5, help='frame hopping for realtime appliance')
    parser.add_argument("--pre_class", nargs='+', type=int, default=[0], help='C0C0 80 classes table')

**Comment by bujianyiwang** [comment]
@nobody-cheng 你好，你的问题解决了吗？

**Comment by Rezmh** [comment]
> 请问有从rtsp流每隔n帧运行yolov3检测实时人数的脚本吗？

你好 请问你是实现对图像内人数计数的功能了吗
