### ISSUE TITLE
convert_weight参数问题

### ISSUE THREAD

**Issue by yyaqi** [wizyoung/YOLOv3_TensorFlow#59]
您好，convert_weight里面的num_class=80是根据coco数据集设置的，请问这个是固定的吗?

**Comment by wizyoung** [comment]
是的，因为要载入原版权重，必须一致。我的理解是，你是不是是想载入除了最后那个分类层以外所有的权重？

**Comment by wizyoung** [comment]
args.py 里面改成 `restore_exclude = ['yolov3/yolov3_head/Conv_14', 'yolov3/yolov3_head/Conv_6', 'yolov3/yolov3_head/Conv_22']` 就可以实现上面那个功能

**Comment by yyaqi** [comment]
> args.py 里面改成 `restore_exclude = ['yolov3/yolov3_head/Conv_14', 'yolov3/yolov3_head/Conv_6', 'yolov3/yolov3_head/Conv_22']` 就可以实现上面那个功能

好的，谢谢
