### ISSUE TITLE
转换成pb模型后，测试图片时，输入节点的张量名字是什么？

### ISSUE THREAD

**Issue by lovepan1** [wizyoung/YOLOv3_TensorFlow#60]
使用bazel解析的输入输出节点为:
--input_layer=phase_train --input_layer_type=bool --input_layer_shape= --output_layer=yolov3/yolov3_head/feature_map_1,yolov3/yolov3_head/feature_map_2,yolov3/yolov3_head/feature_map_3
难道输入张量不应该是图片吗?

**Comment by Byronnar** [comment]
你好大神，请问这个问题解决了嘛，请问你是怎么转换的？

**Comment by pigubaoza** [comment]
import/Placeholder:0
