### ISSUE TITLE
'AverageMeter' object has no attribute 'last_avg'

### ISSUE THREAD

**Issue by qfzack** [wizyoung/YOLOv3_TensorFlow#61]
您好，我在运行train.py到epoch为10的会后需要保存模型，但是出现了如下的错误：
`Traceback (most recent call last):
  File "train.py", line 172, in <module>
    if loss_total.last_avg <= 2.:
AttributeError: 'AverageMeter' object has no attribute 'last_avg'`
我看了一下misc_utils.py文件的AverageMeter类，其中定义了一个函数：
`    def avg(self):
        self.last_avg = self.average
        self.reset()
        return self.last_avg`
是不是应该把loss_total.last_avg改为loss_total.avg ？？
另外，我的训练过程会出现`no box, ignore`是标签数据的问题吗？
非常期待您的回复！

**Comment by wizyoung** [comment]
感谢，已修正。主要是github代码版本和本地不太一致，很多细节疏忽了。
出现 no box 无关紧要，说明网络前期学的不够好，有的图片上没有回归到框，忽略就好。

**Comment by qfzack** [comment]
> 感谢，已修正。主要是github代码版本和本地不太一致，很多细节疏忽了。
> 出现 no box 无关紧要，说明网络前期学的不够好，有的图片上没有回归到框，忽略就好。

非常感谢你的回复！
现在在训练，但是我发现precision很高，但是recall要低很多，而且有的epoch中会出现这种情况：
![image](https://user-images.githubusercontent.com/22722784/57761027-3d78b580-772f-11e9-8340-2c5fd89b1474.png)
