### ISSUE TITLE
咕咕鸡的采坑笔记

### ISSUE THREAD

**Issue by yangyangtiaoguo** [wizyoung/YOLOv3_TensorFlow#62]
准备尝试使用楼主大大的代码来做自己事情，不过发现坑挺多的，写个笔记记录一下完整过程。

**Comment by yangyangtiaoguo** [comment]
第一个小坑，wget https://github.com/YunYang1994/tensorflow-yolov3/releases/download/v1.0/yolov3_coco.tar.gz
可能是我网不好吧，下载了几次才好，然后我去解压他 发现解压到一半失败了，ls发现我这里下载了两个文件，估计有一个是之前下载失败的。所以我真正下载成功的文件名字叫 yolov3_coco.tar.gz.1  
然后解压成功了。
第二个。easydict 这个东西是个包，自己 pip去下载吧。原文依赖没说。
第三个坑。 image_demo.py 遇到了好几个除法分母为零的报错。。。。。尴尬，难道是我集群比较挑剔么。。。。
47行    修改为：scale = min(float(iw)/float(w),float(ih)/float(h))

188行  修改为：resize_ratio = min(float(input_size) / float(org_w), float(input_size) / float(org_h))

完成上述过程，我测试图片成功了。

 不会上传图片。。。突然发现。算了不穿了，我继续接下来的步骤了，希望有人可以说一下，为什么我要加float（）难道你们不用么。。。。。伤心，后面不知道还会有多少这种东西。

**Comment by wizyoung** [comment]
大哥是不是issue发错地方了。。。

**Comment by kazim05** [comment]
can you talk me at wechat.? i have some problems..

**Comment by kazim05** [comment]
@wizyoung

**Comment by yangyangtiaoguo** [comment]
。。。是的好尴尬

**Comment by wizyoung** [comment]
@yangyangtiaoguo 没事没事。那个作者我认识hhh，其实最早的时候我写yolo就是发现github上没有好的yolo3的代码，参考了YunYang1994的代码，发现问题很多就自己重新写了一版手里项目应急，然后发现效果就挺好的。后来和那个作者交流讨论了很久，互相改了一些bug，所以我们核心部分其实很像。最近我们都太忙了，完全没空管。这份代码其实很多小问题我也知道，手里也在重构着，无奈太忙了，只能周末抽空看看。毕竟兴趣不能当饭吃hhh。有什么问题欢迎随时提出来~

**Comment by bujianyiwang** [comment]
请问有从rtsp流每隔n帧跑yolov3检测实时人数的脚本吗？
