### ISSUE TITLE
mixup 有个bug

### ISSUE THREAD

**Issue by schabc** [wizyoung/YOLOv3_TensorFlow#63]

**Comment by schabc** [comment]
![image](https://user-images.githubusercontent.com/34892344/57764729-a0ba1600-7736-11e9-9211-4db427aed8b1.png)
data_utils.py里面，使用mixup的时候，会出问题，这个是我改过后

**Comment by wizyoung** [comment]
谢谢~本地代码和github上的差别有点大，我push的时候很多小bug忽视了

**Comment by wizyoung** [comment]
fixed
