### ISSUE TITLE
IndexError: index 29 is out of bounds for axis 1 with size 26

### ISSUE THREAD

**Issue by ITKing80** [wizyoung/YOLOv3_TensorFlow#64]
错误描述如下：

Traceback (most recent call last):

  File "E:\Python\Python37\Lib\site-packages\tensorflow\python\ops\script_ops.py", line 207, in __call__
    ret = func(*args)

  File "d:\tensorflow\tfyolo3wiz\utils\data_utils.py", line 205, in get_batch_data
    img_idx, img, y_true_13, y_true_26, y_true_52 = parse_data(line, class_num, img_size, anchors, mode)

  File "d:\tensorflow\tfyolo3wiz\utils\data_utils.py", line 166, in parse_data
    y_true_13, y_true_26, y_true_52 = process_box(boxes, labels, img_size, class_num, anchors)

  File "d:\tensorflow\tfyolo3wiz\utils\data_utils.py", line 102, in process_box
    y_true[feature_map_group][y, x, k, :2] = box_centers[i]

IndexError: index 29 is out of bounds for axis 1 with size 26

         [[{{node PyFunc}}]]
         [[node IteratorGetNext (defined at d:\tensorflow\tfyolo3wiz\train.py:60) ]]

我的识别类别只有一个，开始以为是我的识别类别太少了，后面加了20行空行，还是报错。
这是为什么?

**Comment by wizyoung** [comment]
数据不干净

**Comment by ITKing80** [comment]
> 数据不干净

感谢及时回复。
这个怎么理解，我查过了，我每一行数据都有label的。

**Comment by wizyoung** [comment]
坐标越界之类的，这个得你自己debug了

**Comment by ITKing80** [comment]
> 坐标越界之类的，这个得你自己debug了

你指的是做label指定的坐标框越界了？我是用labelImg做的

**Comment by wizyoung** [comment]
这种问题，你把预处理代码拷贝出来单独用Python跑一下，中间加几个断点，就很容易发现问题。比如，会不会有的图片上没有标记。

**Comment by ITKing80** [comment]
好的，谢谢

**Comment by chersonese** [comment]
> 这种问题，你把预处理代码拷贝出来单独用Python跑一下，中间加几个断点，就很容易发现问题。比如，会不会有的图片上没有标记。

有的图片就是不要标记的会影响吗？

**Comment by ITKing80** [comment]
我发现了这个错误的原因，分享出来供后面踩坑的人参考。
我碰到的原因是我的样本照片是手机拍摄的，某些照片具有翻转属性，系统中（windows）直接打开是正常的，但是在labelImg中显示是翻转90度的，这样做的label在翻转后坐标会超出图片，所以会出现out of bounds的问题。

解决办法是编辑异常图片，使其在labelImg中显示正常。

**Comment by wizyoung** [comment]
@chersonese 没有标记不行的。没有标记还放数据集有何意义，没标签不参与训练，数据不会参与反向传播

**Comment by chersonese** [comment]
@wizyoung 好吧，我知道了。谢谢你。

**Comment by lovepan1** [comment]
我也遇到了同样的问题，确实是数据不干净，标注的坐标出错,最后数组越界了，非常感谢

**Comment by greenrachel** [comment]
would I like to reply in English if you don't mind? Because I am getting the same error.

**Comment by wizyoung** [comment]
@greenrachel your data is not clean. You should have at least one target at each line of your txt file.
