### ISSUE TITLE
加载数据很慢

### ISSUE THREAD

**Issue by fengxiuyaun** [wizyoung/YOLOv3_TensorFlow#65]
hi,你好，非常感谢你的分享。现在我再用你的代码，但是发现数据加载这块好像很慢，我认为你仅是在一个线程里加载整个batchsize的图片？

**Comment by wizyoung** [comment]
默认10个线程啊，我这里效率很高，毕竟是 tf.data，nvidia-smi GPU-util 保持在 99%，CPU 是 i7-7700K

**Comment by fengxiuyaun** [comment]
其实有点不明白下边链接，这个for循环难道不是在同一个线程里运行的？假如我batchsize很大，for的次数变多，是不是就变慢了？https://github.com/wizyoung/YOLOv3_TensorFlow/blob/d998369c8213ded2414f470b30000545b4c2f614/utils/data_utils.py#L204

**Comment by wizyoung** [comment]
是的，一个线程通过for循环进行batch操作，但是这一整个操作有10个线程在同时执行。所以怎么会影响速度呢，程序启动后短时间内确实慢一点，马上CPU就填满了队列就不会影响速度了。只要CPU够快就行。事实上，把 batch 操作放在线程里面确实效率更高一点，不然多线程得到单个数据后再进行 batch 操作，batch 的硬延时完全无法缓解。这也是为什么 tf 要提供类似 tf.contrib.map_and_batch 的 api

**Comment by fengxiuyaun** [comment]
嗯嗯。谢谢。或许咱们的应用环境不同。我这里batchsize是128. 网络很小。导致gpu一直在等待cpu读数据

**Comment by wizyoung** [comment]
是不是 cpu 性能不够，batch_size 又太大，每个线程都要进行 batch 操作，导致数据输出不够快

**Comment by fengxiuyaun** [comment]
嗯嗯。有可能。之前版本使用tf.image load128张图片需要0.5S。使用你这种py_fun的话第一个会很慢,大概55S，剩下9个大概0.3S。接下来就是55S，0.3S。应该是10个线程

**Comment by ZH-Lee** [comment]
> 是不是 cpu 性能不够，batch_size 又太大，每个线程都要进行 batch 操作，导致数据输出不够快

请问一下，我用多线程训练的时候都没问题，速度很快，但是在测试集上做eval的时候，速度很慢，而且是越来越慢，最后卡住了。请问怎么回事呢？代码都跟你一样的。

**Comment by wizyoung** [comment]
用的是哪个版本的代码

**Comment by ZH-Lee** [comment]
> 用的是哪个版本的代码

就是现在的版本。我没有完全使用你的整个代码。我只是想用tf.data这个pipeline，所以我把你的这个pipeline代码抄过来了。但是，训练正常， eval很慢。不知道为啥。

**Comment by ZH-Lee** [comment]
> 用的是哪个版本的代码

测试的时候，一开始会有20个batch（测试batch为1）处理完。然后后面就特别慢，且每测试一个batch就变的更慢。

**Comment by wizyoung** [comment]
很奇怪，我这里没有问题。之前老版本的代码train和val切换时会慢，我发现应该是feedable iterator的问题就改了。现在这套流程我已经用了很久了，在多个任务上测试过，没性能问题

**Comment by ZH-Lee** [comment]
> 很奇怪，我这里没有问题。之前老版本的代码train和val切换时会慢，我发现应该是feedable iterator的问题就改了。现在这套流程我已经用了很久了，在多个任务上测试过，没性能问题

可以加个微信帮我看看嘛。我训练代码很短。

**Comment by wizyoung** [comment]
联系方式发我首页邮箱吧

**Comment by ZH-Lee** [comment]
> 联系方式发我首页邮箱吧
我的代码和微信都发你google那个邮箱了

**Comment by ZH-Lee** [comment]
> 很奇怪，我这里没有问题。之前老版本的代码train和val切换时会慢，我发现应该是feedable iterator的问题就改了。现在这套流程我已经用了很久了，在多个任务上测试过，没性能问题

我把测试集和训练集换了个位置试了一下，发现问题还是存在。所以问题应该不是数据集的问题。应该还是代码哪里有bug。实在找不出来了 。网上找了很多tf.data的例子。基本都是一样的。

**Comment by ZH-Lee** [comment]
> 很奇怪，我这里没有问题。之前老版本的代码train和val切换时会慢，我发现应该是feedable iterator的问题就改了。现在这套流程我已经用了很久了，在多个任务上测试过，没性能问题

你好，能帮我看看我的训练代码吗？昨天发你google的邮箱了。
