### ISSUE TITLE
precison较高但是recall很低

### ISSUE THREAD

**Issue by qfzack** [wizyoung/YOLOv3_TensorFlow#68]
您好，我在训练模型的时候，precision可以达到90%以上，但是recall就只有70%多，导致mAP也不高，我想请教一下这个问题可能出在哪里，非常感谢！

**Comment by tianfengyijiu** [comment]
eval中的score_threshold调低一些或者直接设置为0看看

> 您好，我在训练模型的时候，precision可以达到90%以上，但是recall就只有70%多，导致mAP也不高，我想请教一下这个问题可能出在哪里，非常感谢！

**Comment by lcltopismine** [comment]
> eval中的score_threshold调低一些或者直接设置为0看看
> 
> > 您好，我在训练模型的时候，precision可以达到90%以上，但是recall就只有70%多，导致mAP也不高，我想请教一下这个问题可能出在哪里，非常感谢！

score_threshold和这个无关吧

**Comment by wizyoung** [comment]
@lcltopismine 确实是需要降低 score_threshold. 默认的 0.5 比较严苛，导致 recall 不会很高
