### ISSUE TITLE
导入数据集格式问题

### ISSUE THREAD

**Issue by lyz0313** [wizyoung/YOLOv3_TensorFlow#69]
作者您好，想请教一下数据集的导入格式问题。
`0 xxx/xxx/a.jpg 0 453 369 473 391 1 588 245 608 268

1 xxx/xxx/b.jpg 1 466 403 485 422 2 793 300 809 320
`
这个格式的定义是在那个文件中？因为我的标注文件格式不一样，所以我想改一下。

**Comment by tianfengyijiu** [comment]
> 作者您好，想请教一下数据集的导入格式问题。
> `0 xxx/xxx/a.jpg 0 453 369 473 391 1 588 245 608 268
> 
> 1 xxx/xxx/b.jpg 1 466 403 485 422 2 793 300 809 320
> `
> 这个格式的定义是在那个文件中？因为我的标注文件格式不一样，所以我想改一下。

要改很多地方，至少把datautils中的get_batch_data前后都改掉，还有tf张量的形状也要跟着改

**Comment by zjjzjj123** [comment]
> 作者您好，想请教一下数据集的导入格式问题。
> `0 xxx/xxx/a.jpg 0 453 369 473 391 1 588 245 608 268
> 
> 1 xxx/xxx/b.jpg 1 466 403 485 422 2 793 300 809 320
> `
> 这个格式的定义是在那个文件中？因为我的标注文件格式不一样，所以我想改一下。

you complete? i dont know to do

**Comment by lyz0313** [comment]
> > 作者您好，想请教一下数据集的导入格式问题。
> > `0 xxx/xxx/a.jpg 0 453 369 473 391 1 588 245 608 268
> > 1 xxx/xxx/b.jpg 1 466 403 485 422 2 793 300 809 320
> > `
> > 这个格式的定义是在那个文件中？因为我的标注文件格式不一样，所以我想改一下。
> 
> 要改很多地方，至少把datautils中的get_batch_data前后都改掉，还有tf张量的形状也要跟着改

谢了，我还是把我的数据的格式改一下好了。
