### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '(294).JPG'

### ISSUE THREAD

**Issue by henbucuoshanghai** [wizyoung/YOLOv3_TensorFlow#70]
第一次训练，出现的

**Comment by smoolya17** [comment]
@henbucuoshanghai may you explain how you resolved this issue?

**Comment by as1392** [comment]
@smoolya17 Be careful when making val.txt, especially don't miss image_index!

**Comment by smoolya17** [comment]
Yes
