### ISSUE TITLE
关于训练数据种类的问题

### ISSUE THREAD

**Issue by lyz0313** [wizyoung/YOLOv3_TensorFlow#72]
作者您好：
您的代码，对于标注数据的种类是从0开始的吧？比如10个种类就是0到9.
但是我的数据是从1开始的，是1到10.
请问您的源码中可以怎么修改呢？

**Comment by tianfengyijiu** [comment]
misc_utils.py中read_class_names函数改成：
names[ID] = name.strip('\n')  -> names[ID + 1] = name.strip('\n')

**Comment by lyz0313** [comment]
> misc_utils.py中read_class_names函数改成：
> names[ID] = name.strip('\n') -> names[ID + 1] = name.strip('\n')

谢谢，我会试一试
