### ISSUE TITLE
AttributeError: 'AverageMeter' object has no attribute 'last_avg'

### ISSUE THREAD

**Issue by henbucuoshanghai** [wizyoung/YOLOv3_TensorFlow#73]
trained 80 epoched，and stoped by this problem....................why?????

AttributeError: 'AverageMeter' object has no attribute 'last_avg'

**Comment by henbucuoshanghai** [comment]
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    saver_to_save.save(sess, args.save_dir + 'model-epoch_{}_step_{}_loss_{:.4f}_lr_{:.5g}'.format(epoch, int(__global_step), loss_total.last_avg, __lr))
AttributeError: 'AverageMeter' object has no attribute 'last_avg'

**Comment by qfzack** [comment]
change 'last_avg' to ‘avg’

**Comment by henbucuoshanghai** [comment]
ValueError: all the input arrays must have same number of dimensions


what is wrong?
