### ISSUE TITLE
达不到Darknet的效果

### ISSUE THREAD

**Issue by tianfengyijiu** [wizyoung/YOLOv3_TensorFlow#79]
作者你好，我用你实现的YOLOv3训练VOC数据集，达不到darknet的70+的mAP，只有51，请问是为什么

**Comment by wizyoung** [comment]
才51吗？早期没有加任何数据增广，我在voc上训了一晚上，就有70的mAP了，后面就没训过了，你是不是参数没调好啥的

**Comment by wizyoung** [comment]
最近太忙了，哪个周末有空的话我再试着训训看吧

**Comment by tianfengyijiu** [comment]
eval的时候的参数应该是多少，默认的与darknet保持一样了吗？在IOU_threshold=0.5,score_threshold=0.5下得到0.51，继续训练十万轮后才有0.64。另外博主能否告诉我darknet的eval程序IOU_threshold和score_threshold分别是多少？

**Comment by tianfengyijiu** [comment]
可以加一下微信沟通一下吗？谢谢，wx：13207695810

**Comment by huangzheng001** [comment]
您好，测mAP时，score_threshold 是如何选择的？为何不设为0呢？

**Comment by wizyoung** [comment]
@huangzheng001 刷指标的话 score_threshold 就设置低一点，比如 0.001，0.01 都挺好。实际项目用的话还是设置偏大的值比较好。这份代码主要是给大家提供一种参考
