### ISSUE TITLE
请问支持多gpu训练吗？

### ISSUE THREAD

**Issue by lovepan1** [wizyoung/YOLOv3_TensorFlow#80]
我使用os.environ["CUDA_VISIBLE_DEVICES"] = '0,1' ,训练时并没有使用两个gpu，即使使用os.environ["CUDA_VISIBLE_DEVICES"] = '1' 指定gpu1也还是使用gpu0训练，请问这个情况是属于我的配置问题吗？还是必须得设置不同的变量使用不同的gpu，最后梯度再使用cpu进行运算？新手求指导

**Comment by lallallalu** [comment]
i want to know :(

**Comment by wscjxky** [comment]
i want to know too

**Comment by lovepan1** [comment]
https://github.com/panchengl/yolov3_prune&nbsp; &nbsp;&nbsp;
u can use，if u think helpful, please give me a star, thank u

---原始邮件---
发件人: "Stanley"<notifications@github.com&gt;
发送时间: 2020年11月25日(周三) 中午11:13
收件人: "wizyoung/YOLOv3_TensorFlow"<YOLOv3_TensorFlow@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"lovepan1"<312287965@qq.com&gt;;
主题: Re: [wizyoung/YOLOv3_TensorFlow] 请问支持多gpu训练吗？ (#80)




 
i want to know too

**Comment by lovepan1** [comment]
https://github.com/panchengl/yolov3_prune
u can use，if u think helpful, please give me a star, thank u

**Comment by wscjxky** [comment]
> https://github.com/panchengl/yolov3_prune
> u can use，if u think helpful, please give me a star, thank u

thanks ! i will checkout right now
