### ISSUE TITLE
eval_utils.py 錯誤

### ISSUE THREAD

**Issue by Leyan529** [wizyoung/YOLOv3_TensorFlow#82]
![image](https://user-images.githubusercontent.com/24097516/58385500-fa1e2100-8023-11e9-8a8c-bfbf7231ced7.png)

![image](https://user-images.githubusercontent.com/24097516/58385518-33ef2780-8024-11e9-99ab-4a40e8607f2c.png)

我的data
[train.txt](https://github.com/wizyoung/YOLOv3_TensorFlow/files/3220958/train.txt)
[val.txt](https://github.com/wizyoung/YOLOv3_TensorFlow/files/3220959/val.txt)

順便在問一下
data_utils.py裡面這個line_idx代表時麼意思
![image](https://user-images.githubusercontent.com/24097516/58385545-87617580-8024-11e9-94e1-9ca9597b27cd.png)

**Comment by wizyoung** [comment]
就是行号，第一行的图片行号为0，其实为任意数都可以，不重复就行。这个主要是方便后面测试指标和找出 bad case 用
