### ISSUE TITLE
计算loss的函数是不是有些错误？

### ISSUE THREAD

**Issue by LordkTk** [wizyoung/YOLOv3_TensorFlow#85]
在`model.py`文件的`loss_layer`函数中，用
`# shape: [N, 13, 13, 3, 4] & [N, 13, 13, 3] ==> [V, 4]`
`tf.boolean_mask(y_true[..., 0:4], tf.cast(object_mask[..., 0], 'bool'))` 
这一语句来得到所有真实框的中心及宽高，之后用下面的`broadcast_iou()`函数计算每个检测器预测框与真实框的iou，如果某个检测器与某个真实框的iou大于阈值，就忽略这个检测器的no_object_loss。
但问题是，以上得到的`[V, 4]`的张量，包含的应该是这个batch（例如64）里所有图片真实框的总和，而不是单个图片的，这应该是不对的。因为这个操作的本意是忽略掉那些 本不该检测到物体但检测结果却挺好的检测器 的loss。这样相当于增加了每张图片里的真实框数量，应该会使no_object_loss格外小。
不知道我的理解是否有错，希望作者有空的时候可以回复一下，感谢。

**Comment by wizyoung** [comment]
方面留微信或者其他IM吗，我们交流下

**Comment by LordkTk** [comment]
好的，我的微信号是：lordkTk
感谢您的回复
在2019年6月2日 18:56，Wizyoung<notifications@github.com> 写道：

方面留微信或者其他IM吗，我们交流下

**Comment by factplay1** [comment]
Is this issue solved? I'm very curious...
