### ISSUE TITLE
训练自己数据的话训练的图片都要resized到同一尺寸吗

### ISSUE THREAD

**Issue by ZouDongj** [wizyoung/YOLOv3_TensorFlow#86]
**You may need to resize the anchors to your target training image size before training and write them to the anchors txt file**
是不是训练数据要统一尺寸然后再resize anchors呢？我的数据尺寸不同意，尝试get kmeans的时候，每次运行的到的结果都不一样，是因为图片尺寸不统一的问题吗？

**Comment by wizyoung** [comment]
see https://github.com/wizyoung/YOLOv3_TensorFlow/issues/54
