### ISSUE TITLE
train from scratch

### ISSUE THREAD

**Issue by ZH-Lee** [wizyoung/YOLOv3_TensorFlow#87]
你好，代码很不错。请问你试过train from scratch吗？就是不加载draknet53的预训练模型，从头开始训练。因为我想把backbone换成其他的轻量级网络。所以想请教下。

**Comment by wizyoung** [comment]
你指的是只载入darknet53分类器部分权重，还是完全不载入模型？只载入分类器部分挺好训练的
换 backbone 和载入分类器权重不冲突吧
