### ISSUE TITLE
Filepath failed to resolve 

### ISSUE THREAD

**Issue by Cli98** [wizyoung/YOLOv3_TensorFlow#91]
The get_kmeans.py file failed to extract the filepath with space inside.

Here is an example of ERROR

input:
1 .\image_data\raw_images\abc def GH.rpg 0 111 111 111 111
ValueError: could not convert string to float: 'def'

I have provided a solution, please consider to merge it in PR.

**Comment by wizyoung** [comment]
Where is your solution?

**Comment by ahmedselim2017** [comment]
What is the solution?
