### ISSUE TITLE
How to restore the global steps and learning rate

### ISSUE THREAD

**Issue by tianfengyijiu** [wizyoung/YOLOv3_TensorFlow#94]
When I try to restore the checkpoint to continue the train, the global steps and learning rate has been reset, how can I restore the global steps and learning rate?

**Comment by wizyoung** [comment]
see https://github.com/wizyoung/YOLOv3_TensorFlow/blob/master/train.py#L92, just change the global_step param in args.py

**Comment by tianfengyijiu** [comment]
Can we save the global steps in checkpoint files and restore it? And learning rate?

**Comment by wizyoung** [comment]
yes, remove the global_step from tf.GraphKeys.LOCAL_VARIABLES may work (I forgot the details). You can have a try

**Comment by tianfengyijiu** [comment]
well, I modify the code as :
global_step = tf.Variable(0, name='global_step', trainable=False
and:
saver.save(sess, save_path, global_step=global_step)
then it works.
