### ISSUE TITLE
other training strategies

### ISSUE THREAD

**Issue by Cli98** [wizyoung/YOLOv3_TensorFlow#98]
Wonder if any one can give me some hints for "other training strategies" that author implemented in this repo(Reference, paper, etc). Many thanks.

**Comment by wizyoung** [comment]
Please refer to this paper: https://arxiv.org/abs/1902.04103

**Comment by Cli98** [comment]
> Please refer to this paper: https://arxiv.org/abs/1902.04103

Thank you for your kindly support.
